import Foundation
import Testing

@Test func simulationViewModelDoesNotOwnTrainingLoopController() throws {
    let source = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")

    #expect(!source.contains("TrainingLoopController("))
    #expect(!source.contains("trainingLoopController"))
}

@Test func configPanelDoesNotBindDescriptorPathDirectly() throws {
    let source = try readSource("Sources/KuyuUI/Views/ConfigPanelView.swift")

    #expect(!source.contains("$model.modelDescriptorPath"))
    #expect(source.contains("setModelDescriptorPath("))
}

@Test func commandSystemOwnsTrainingLoopExecutionBoundary() throws {
    let source = try readSource("Sources/KuyuUI/Services/CommandSystem.swift")
    let trainingService = try readSource("Sources/KuyuUI/Services/TrainingService.swift")

    #expect(source.contains("TrainingLoopController(commandExecutor: self)"))
    #expect(source.contains("extension CommandSystem: TrainingLoopCommandExecuting"))
    #expect(source.contains("TrainingRunOrchestrator("))
    #expect(source.contains("ManasMLXTrainingBackendFactory().makeWorkerLocalBackend"))
    #expect(source.contains("sourceSnapshot: backendBundle.sourceSnapshot"))
    #expect(source.contains("extension CommandSystem: TrainingScenarioExecuting"))
    #expect(source.contains("runSuiteForTrainingRun"))
    #expect(trainingService.contains("ManasMLXTrainingRuntime"))
    #expect(trainingService.contains("TrainingBackendRequest("))
    #expect(!trainingService.contains(".trainCore("))
}

@Test func trainingLoopControllerDelegatesToSharedOrchestratorContract() throws {
    let source = try readSource("Sources/KuyuUI/Services/TrainingLoopController.swift")
    let adapterSource = try readSource("Sources/KuyuUI/Services/TrainingLoopEventAdapter.swift")
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")

    #expect(source.contains("runTrainingRunForTrainingLoop"))
    #expect(source.contains("TrainingRunConfig("))
    #expect(source.contains("TrainingLoopEventAdapter.present"))
    #expect(source.contains("TrainingLoopEventAdapter.presentCompletion"))
    #expect(adapterSource.contains("TrainingRunEvent"))
    #expect(adapterSource.contains("TrainingLoopSummary("))
    #expect(!source.contains("exportDatasetForTrainingLoop"))
    #expect(!source.contains("trainCoreForTrainingLoop"))
    #expect(cliSource.contains("TrainingRunOrchestrator("))
    #expect(cliSource.contains("ProbeManas.self"))
    #expect(cliSource.contains("TrainingProbeOrchestrator("))
    #expect(cliSource.contains("KuyuScenarioRuntime("))
    #expect(!cliSource.contains("probe-manas currently supports attitude only"))
    #expect(cliSource.contains("let scenarioStore = ManasMLXModelStore()"))
    #expect(cliSource.contains("let workerStore = ManasMLXModelStore()"))
    #expect(cliSource.contains("CLIScenarioExecutor("))
}

@Test func serviceDescriptorFailureLogsCarryRequiredMetadataKeys() throws {
    let source = try readSource("Sources/KuyuUI/Services/SimulationRunnerService.swift")

    #expect(source.contains("\"action\": \"descriptorLoadFailed\""))
    #expect(source.contains("\"modelDescriptor\""))
    #expect(source.contains("\"reason\": \"loadFailed\""))
    #expect(source.contains("\"error\""))
}

@Test func simulationViewModelDelegatesDescriptorAndTelemetryProjection() throws {
    let source = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let coordinatorSource = try readSource("Sources/KuyuUI/Services/TrainingRunCoordinator.swift")
    let bootstrapSource = try readSource("Sources/KuyuUI/Services/TrainingBootstrapCoordinator.swift")

    #expect(source.contains("DescriptorSelection.resolveForTask"))
    #expect(source.contains("telemetryPresenter.present"))
    #expect(source.contains("descendingIntentResolver.resolve"))
    #expect(source.contains("trainingRunPresenter.runCompleted"))
    #expect(source.contains("checkpointStore.persist"))
    #expect(source.contains("trainingRunCoordinator.prepare"))
    #expect(source.contains("trainingBootstrapCoordinator.makeRequest"))
    #expect(coordinatorSource.contains("TrainingRunPreparationInput"))
    #expect(coordinatorSource.contains("TrainingLoopConfig("))
    #expect(coordinatorSource.contains("SimulationRunRequest("))
    #expect(bootstrapSource.contains("TrainingBootstrapInput"))
    #expect(bootstrapSource.contains("TrainingRequest("))
    #expect(!source.contains("metadata[\"u_out_thrust\"]"))
    #expect(!source.contains("metadata[\"netAccelZ\"]"))
    #expect(!source.contains("private func parseDescending"))
    #expect(!source.contains("ScenarioMetricsBuilder.build"))
    #expect(!source.contains("modelStore.saveModel("))
}

@Test func trainingRunStoreIsArtifactDriven() throws {
    let source = try readSource("Sources/KuyuUI/Services/TrainingRunStore.swift")
    let controllerSource = try readSource("Sources/KuyuUI/Services/TrainingLoopController.swift")
    let adapterSource = try readSource("Sources/KuyuUI/Services/TrainingLoopEventAdapter.swift")
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let validatorSource = try readTrainingSource("Sources/KuyuTraining/TrainingRunArtifactValidator.swift")
    let artifactSource = try readTrainingSource("Sources/KuyuTraining/TrainingArtifacts.swift")

    #expect(source.contains("TrainingRunArtifactValidator"))
    #expect(source.contains("TrainingMetricRecord"))
    #expect(source.contains(".validationLoss"))
    #expect(source.contains(".passRate"))
    #expect(source.contains(".failureRate"))
    #expect(source.contains(".safetyViolation"))
    #expect(source.contains(".rewardAverage"))
    #expect(source.contains(".workerThroughput"))
    #expect(artifactSource.contains("artifact-contract.json"))
    #expect(validatorSource.contains("manifest.json"))
    #expect(validatorSource.contains("metrics.jsonl"))
    #expect(validatorSource.contains("convergence.json"))
    #expect(validatorSource.contains("checkpoint-decision.json"))
    #expect(controllerSource.contains("TrainingLoopEventAdapter.presentCompletion"))
    #expect(adapterSource.contains("artifactDirectory: artifactDirectory"))
    #expect(adapterSource.contains("checkpointDecision: result.checkpointDecision"))
    #expect(viewModelSource.contains("trainingRunStore.load"))
    #expect(viewModelSource.contains("lastConvergenceSummary"))
    #expect(viewModelSource.contains("lastCheckpointDecision"))
}

@Test func trainingDashboardShowsLiveLearningHealthAndGateState() throws {
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let dashboardSource = try readSource("Sources/KuyuUI/Views/TrainingDashboardView.swift")
    let liveStatusSource = try readSource("Sources/KuyuUI/Model/TrainingLiveStatus.swift")

    #expect(liveStatusSource.contains("struct TrainingLiveStatus"))
    #expect(viewModelSource.contains("trainingLiveStatus"))
    #expect(viewModelSource.contains("trainingTimeline"))
    #expect(viewModelSource.contains("updateRunQualityStatus"))
    #expect(viewModelSource.contains("passRateSamples"))
    #expect(viewModelSource.contains("safetyViolationSamples"))
    #expect(viewModelSource.contains("workerThroughputSamples"))
    #expect(dashboardSource.contains("TrainingLiveHealthPanel"))
    #expect(dashboardSource.contains("TrainingGatePanel"))
    #expect(dashboardSource.contains("PostRegressionGatePanel"))
    #expect(dashboardSource.contains("TrainingTimelinePanel"))
    #expect(dashboardSource.contains("Post Regression Gate"))
    #expect(dashboardSource.contains("Worker Throughput Min"))
    #expect(dashboardSource.contains("Rollouts / Episodes"))
    #expect(dashboardSource.contains("Hold Ratio Min"))
    #expect(dashboardSource.contains("Altitude Ratio Max"))
    #expect(dashboardSource.contains("Worst Case"))
    #expect(viewModelSource.contains("RegressionRunStore"))
    #expect(viewModelSource.contains("lastPostRegressionGate"))
    #expect(dashboardSource.contains("Pass Rate"))
    #expect(dashboardSource.contains("Safety Violation"))
    #expect(dashboardSource.contains("Worker Throughput"))
}

@Test func cliHarnessUsesProbeSelectedCheckpointContract() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let probeSource = try readTrainingSource("Sources/KuyuTraining/TrainingProbeOrchestrator.swift")
    let validatorSource = try readTrainingSource("Sources/KuyuTraining/TrainingProbeArtifactValidator.swift")
    let regressionArtifactSource = try readSource("Sources/KuyuMLX/KuyuRegressionArtifacts.swift")

    #expect(probeSource.contains("selectedCheckpointRole"))
    #expect(probeSource.contains("sourceCheckpointURL"))
    #expect(probeSource.contains("selectedCheckpointURL"))
    #expect(validatorSource.contains("validateSelectedCheckpoint"))
    #expect(validatorSource.contains("candidate checkpoint cannot be selected when probe is rejected"))
    #expect(cliSource.contains("selectedCandidateCheckpointURL(result.comparison)"))
    #expect(cliSource.contains("sourceCheckpointURL(from: sourceCheckpointPath)"))
    #expect(cliSource.contains("repairSourceCheckpointURL(from: result)"))
    #expect(cliSource.contains("currentSourceCheckpointURL = repairSourceCheckpointURL"))
    #expect(cliSource.contains("result.training.checkpointDecision.candidateCheckpointURL"))
    #expect(cliSource.contains("TrainingHarnessGateReport"))
    #expect(regressionArtifactSource.contains("public struct KuyuRegressionGateReport"))
    #expect(cliSource.contains("gateReport: gateReport"))
    #expect(cliSource.contains("post-regression-failed"))
    #expect(cliSource.contains("post-regression-min-reward-average"))
    #expect(cliSource.contains("min-reward-average"))
    #expect(cliSource.contains("reward-average-below-min"))
    #expect(cliSource.contains("post-regression-reward-average-below-min"))
    #expect(cliSource.contains("postRegressionAcceptanceSatisfied(postRegression)"))
    #expect(cliSource.contains("postRegressionApplicable(regression)"))
    #expect(cliSource.contains("primaryRejectReason"))
    #expect(cliSource.contains("taskPassRate"))
    #expect(cliSource.contains("minimumHoldTimeRatio"))
    #expect(cliSource.contains("maximumAltitudeErrorRatio"))
    #expect(cliSource.contains("worstScenarioID"))
    #expect(!cliSource.contains("regression.rolloutSuites.first"))
    #expect(!cliSource.contains("firstEntry?.taskQuality.first"))
    #expect(cliSource.contains("tasks: [simulationTaskMode(from: task)]"))
    #expect(cliSource.contains("regressionRolloutTask(selectedTasks)"))
    #expect(cliSource.contains("makeRegressionRolloutDefinitions"))
    #expect(cliSource.contains("TaskEvaluationProfile.profile"))
    #expect(cliSource.contains("regressionProfile.motorNerveSettings"))
    #expect(!cliSource.contains("regressionMotorNerveSettings"))
    #expect(cliSource.contains("RunLearningCampaign.self"))
    #expect(cliSource.contains("commandName: \"run-learning-campaign\""))
    #expect(cliSource.contains("--source-checkpoint is required."))
    #expect(cliSource.contains("LearningCampaignOrchestrator"))
    #expect(!cliSource.contains("suiteForDefinitions = regressionTask == .attitude ? suite : nil"))
    #expect(cliSource.contains("taskFailureCount == 0"))
    #expect(cliSource.contains("evaluateRegressionEpisodes("))
    #expect(cliSource.contains("selected-checkpoint-not-candidate"))
    #expect(cliSource.contains("teacher-divergence-regression"))
    #expect(!cliSource.contains("?? result.training.checkpointDecision.candidateCheckpointURL"))
}

@Test func cliRegressionGateRequiresTaskPassAndRewardQuality() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let artifactsSource = try readSource("Sources/KuyuMLX/KuyuRegressionArtifacts.swift")
    let qualityGateSource = try readSource("Sources/KuyuMLX/KuyuRegressionQualityGatePolicy.swift")
    let gateSource = try readSource("Sources/KuyuMLX/KuyuRegressionGatePolicy.swift")
    let validatorSource = try readSource("Sources/KuyuMLX/KuyuRegressionArtifactValidator.swift")

    #expect(cliSource.contains("KuyuRegressionGatePolicy.report"))
    #expect(cliSource.contains("CheckKuyuRegressionMatrix"))
    #expect(cliSource.contains("kuyu-regression-matrix-summary.json"))
    #expect(cliSource.contains("KuyuRegressionQualityGatePolicy.minimumRewardAverage"))
    #expect(qualityGateSource.contains("defaultMinimumRewardAverage(for task: String)"))
    #expect(qualityGateSource.contains("case \"lift\", \"singleLift\""))
    #expect(qualityGateSource.contains("override ?? defaultMinimumRewardAverage(for: task)"))
    #expect(qualityGateSource.contains("referenceEvaluatorID"))
    #expect(qualityGateSource.contains("TaskEvaluationProfile.profile(task: task)"))
    #expect(qualityGateSource.contains("minimumTaskPassRate: profile?.minimumTaskPassRate"))
    #expect(qualityGateSource.contains("liftThresholdSource: profile?.liftThresholdSource"))
    #expect(qualityGateSource.contains("scenario.liftEnvelope"))
    #expect(gateSource.contains("taskPassCount != entry.episodeCount"))
    #expect(gateSource.contains("task-pass-mismatch"))
    #expect(gateSource.contains("task-pass-rate-below-min"))
    #expect(gateSource.contains("entry.rewardAverage < minimumRewardAverage"))
    #expect(gateSource.contains("reward-average-below-min"))
    #expect(cliSource.contains("gateReport.accepted"))
    #expect(cliSource.contains("allPassed: gateReport.accepted"))
    #expect(artifactsSource.contains("qualityGateTask"))
    #expect(artifactsSource.contains("taskQuality"))
    #expect(artifactsSource.contains("KuyuRegressionQualityRequirement"))
    #expect(artifactsSource.contains("qualityEvaluatorID"))
    #expect(artifactsSource.contains("minimumHoldTimeRatio"))
    #expect(artifactsSource.contains("requiresReferenceTaskPass"))
    #expect(artifactsSource.contains("liftThresholdSource"))
    #expect(validatorSource.contains("public struct KuyuRegressionArtifactValidator"))
    #expect(validatorSource.contains("unsupportedSchemaVersion"))
    #expect(validatorSource.contains("gateReportMismatch"))
    #expect(validatorSource.contains("invalidTaskQualityCount"))
    #expect(validatorSource.contains("nonFiniteTaskQuality"))
    #expect(validatorSource.contains("rolloutPassedMismatch"))
    #expect(cliSource.contains("loadAndValidate(from: artifactRoot)"))
}

@Test func cliHarnessFeedsRecoveryDatasetsIntoLaterAttempts() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let trainingSource = try readTrainingSource("Sources/KuyuTraining/TrainingRunOrchestrator.swift")
    let singlePropRelabelerSource = try readTrainingSource("Sources/KuyuTraining/SinglePropRecoveryRelabeler.swift")
    let liftRelabelerSource = try readTrainingSource("Sources/KuyuTraining/LiftRecoveryRelabeler.swift")

    #expect(trainingSource.contains("additionalDatasetURLs"))
    #expect(trainingSource.contains("additionalDatasetRepeatCount"))
    #expect(trainingSource.contains("TrainingDatasetMixer().mix"))
    #expect(cliSource.contains("acceptedRecoveryDatasetURL(from: result)"))
    #expect(cliSource.contains("recoveryDatasetURLs.append(recoveryDatasetURL)"))
    #expect(cliSource.contains("additionalDatasetURLs: recoveryDatasetURLs"))
    #expect(cliSource.contains("additionalDatasetRepeatCount: recoveryRepeat"))
    #expect(cliSource.contains("--recovery-repeat"))
    #expect(cliSource.contains("includeOnlyFailedScenarios: !includeSuccessfulScenarios"))
    #expect(cliSource.contains("includeSuccessfulScenarios: Bool"))
    #expect(cliSource.contains("LiftRecoveryRelabeler()"))
    #expect(cliSource.contains("KuyLiftSuite().scenarios()"))
    #expect(cliSource.contains("SinglePropRecoveryRelabeler()"))
    #expect(cliSource.contains("KuySingleLiftSuite().scenarios()"))
    #expect(singlePropRelabelerSource.contains("SinglePropHoverCut"))
    #expect(liftRelabelerSource.contains("LiftRecoveryRelabelConfig"))
    #expect(liftRelabelerSource.contains("teacherDrives"))
    #expect(liftRelabelerSource.contains("DriveIntent(index: DriveIndex(3)"))
}

@Test func mlxDatasetLoadingIsDeterministicForHarnessMixing() throws {
    let mlxSource = try readSource("Sources/KuyuMLX/ManasMLXModelStore.swift")
    let trainingSource = try readTrainingSource("Sources/KuyuTraining/TrainingRunOrchestrator.swift")

    #expect(mlxSource.contains(".sorted { $0.lastPathComponent < $1.lastPathComponent }"))
    #expect(trainingSource.contains("sources: repeatedAdditionalDatasetURLs + [exportedDatasetDirectory]"))
}

@Test func simulationViewModelDelegatesLoopStateReduction() throws {
    let source = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let reducerSource = try readSource("Sources/KuyuUI/Services/TrainingLoopStateReducer.swift")

    #expect(source.contains("trainingLoopReducer.reduce"))
    #expect(source.contains("currentTrainingLoopState()"))
    #expect(source.contains("applyTrainingLoopState("))
    #expect(reducerSource.contains("struct TrainingLoopStateReducer"))
    #expect(reducerSource.contains("TrainingLoopStateSnapshot"))
    #expect(reducerSource.contains("case .completed"))
    #expect(!source.contains("loopStatusMessage = \"Iteration \\(iteration)\""))
}

@Test func snapshotBackendContractStaysOutsideMLXImplementation() throws {
    let contract = try readTrainingSource("Sources/KuyuTraining/TrainingBackendSnapshot.swift")
    let workerSnapshot = try readTrainingSource("Sources/KuyuTraining/WorkerSnapshot.swift")
    let workerPlan = try readTrainingSource("Sources/KuyuTraining/ParallelTrainingWorkerPlan.swift")
    let checkpointDecision = try readTrainingSource("Sources/KuyuTraining/CheckpointDecision.swift")
    let reinforcementContract = try readTrainingSource("Sources/KuyuTraining/ReinforcementTrainingBackend.swift")
    let learningRunTypes = try readTrainingSource("Sources/KuyuTraining/LearningRunTypes.swift")
    let orchestrator = try readTrainingSource("Sources/KuyuTraining/TrainingRunOrchestrator.swift")
    let mlxBackend = try readSource("Sources/KuyuMLX/ManasMLXTrainingBackend.swift")
    let mlxBackendFactory = try readSource("Sources/KuyuMLX/ManasMLXTrainingBackendFactory.swift")
    let mlxSnapshotProvider = try readSource("Sources/KuyuMLX/ManasMLXSnapshotProvider.swift")
    let mlxRuntime = try readSource("Sources/KuyuMLX/ManasMLXTrainingRuntime.swift")
    let loopController = try readSource("Sources/KuyuUI/Services/TrainingLoopController.swift")

    #expect(contract.contains("public protocol SnapshotTrainingBackend"))
    #expect(contract.contains("TrainingBackendSnapshot"))
    #expect(reinforcementContract.contains("public protocol ReinforcementTrainingBackend"))
    #expect(reinforcementContract.contains("ReinforcementTrainingWorkerMetric"))
    #expect(learningRunTypes.contains("workerIndex: Int?"))
    #expect(learningRunTypes.contains("snapshotID: String?"))
    #expect(learningRunTypes.contains("rolloutShardURL: URL?"))
    #expect(orchestrator.contains("workerMetricRecords"))
    #expect(loopController.contains("case reinforcementTrainingCompleted"))
    #expect(workerSnapshot.contains("public struct WorkerSnapshot"))
    #expect(workerSnapshot.contains("public protocol SnapshotProviding"))
    #expect(workerPlan.contains("public struct ParallelTrainingWorkerPlan"))
    #expect(workerPlan.contains("rolloutShardURL"))
    #expect(reinforcementContract.contains("workerPlan: ParallelTrainingWorkerPlan?"))
    #expect(checkpointDecision.contains("public struct CheckpointDecision"))
    #expect(checkpointDecision.contains("public struct CheckpointRepository"))
    #expect(mlxBackend.contains("SnapshotTrainingBackend"))
    #expect(mlxBackend.contains("ManasMLXTrainingRuntime"))
    #expect(mlxBackend.contains("checkpointDirectory(for: request)"))
    #expect(mlxBackendFactory.contains("let workerStore = ManasMLXModelStore()"))
    #expect(mlxBackendFactory.contains("candidate-checkpoints"))
    #expect(mlxBackendFactory.contains("source-checkpoint"))
    #expect(mlxSnapshotProvider.contains("SnapshotProviding"))
    #expect(mlxSnapshotProvider.contains("workerRootURL"))
    #expect(mlxSnapshotProvider.contains("copyItem"))
    #expect(!mlxBackend.contains("modelStore: ManasMLXModelStore"))
    #expect(!mlxBackend.contains(".trainCore("))
    #expect(mlxRuntime.contains(".trainCore("))
    #expect(mlxRuntime.contains("request.sourceSnapshot"))
    #expect(mlxRuntime.contains(".loadModel("))
}

@Test func evolutionContractKeepsKuyuAsHarnessAndMLXAsVariationBackend() throws {
    let runTypes = try readTrainingSource("Sources/KuyuTraining/EvolutionRunTypes.swift")
    let backendContract = try readTrainingSource("Sources/KuyuTraining/EvolutionBackend.swift")
    let orchestrator = try readTrainingSource("Sources/KuyuTraining/EvolutionRunOrchestrator.swift")
    let artifacts = try readTrainingSource("Sources/KuyuTraining/EvolutionArtifacts.swift")
    let validator = try readTrainingSource("Sources/KuyuTraining/EvolutionArtifactValidator.swift")
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let mlxEvolution = try readSource("Sources/KuyuMLX/ManasMLXEvolutionBackend.swift")

    #expect(runTypes.contains("public struct GenomeCandidate"))
    #expect(runTypes.contains("public struct FitnessSummary"))
    #expect(runTypes.contains("teacherDelta: Double?"))
    #expect(runTypes.contains("public enum EvolutionSearchStrategy"))
    #expect(runTypes.contains("case antitheticEvolutionStrategy"))
    #expect(runTypes.contains("case qualityDiversity"))
    #expect(runTypes.contains("public struct EvolutionAdaptiveMutationConfig"))
    #expect(runTypes.contains("behaviorDescriptor: [String: Double]"))
    #expect(runTypes.contains("antitheticPairID: String?"))
    #expect(runTypes.contains("commonRandomSeed: UInt64"))
    #expect(runTypes.contains("isIncumbent: Bool?"))
    #expect(backendContract.contains("public protocol EvolutionaryTrainingBackend"))
    #expect(backendContract.contains("public protocol EvolutionCandidateEvaluating"))
    #expect(backendContract.contains("mutationNoiseScale"))
    #expect(orchestrator.contains("EvolutionRunOrchestrator"))
    #expect(orchestrator.contains("backend.seedPopulation"))
    #expect(orchestrator.contains("backend.produceNextGeneration"))
    #expect(orchestrator.contains("EvolutionQualityDiversityArchiveBuilder"))
    #expect(orchestrator.contains("nextMutationSchedule"))
    #expect(artifacts.contains("evolution-manifest.json"))
    #expect(artifacts.contains("fitness.jsonl"))
    #expect(artifacts.contains("accepted-checkpoint.json"))
    #expect(artifacts.contains("quality-diversity-archive.json"))
    #expect(validator.contains("nonFiniteFitness"))
    #expect(validator.contains("lineageMismatch"))
    #expect(validator.contains("qualityDiversityCandidateMissing"))
    #expect(validator.contains("nonFiniteQualityDiversityCell"))
    #expect(mlxEvolution.contains("ManasMLXGenomeVariationProviding"))
    #expect(mlxEvolution.contains("ManasMLXGaussianMutationProvider"))
    #expect(mlxEvolution.contains("MLXRandom.normal"))
    #expect(mlxEvolution.contains("antitheticPairID"))
    #expect(mlxEvolution.contains("antitheticSign"))
    #expect(mlxEvolution.contains("parentCheckpointURLs"))
    #expect(mlxEvolution.contains("preserveIncumbent: true"))
    #expect(mlxEvolution.contains("candidatePreservesIncumbent ? 0 : mutationRate"))
    #expect(mlxEvolution.contains("isIncumbent: request.isIncumbent"))
    #expect(mlxEvolution.contains("ManasMLXEvolutionBackend"))
    #expect(mlxEvolution.contains("EvolutionaryTrainingBackend"))
    #expect(cliSource.contains("EvolveManas.self"))
    #expect(cliSource.contains("commandName: \"evolve-manas\""))
    #expect(cliSource.contains("CLIEvolutionRegressionEvaluator"))
    #expect(cliSource.contains("CLICandidateOnlyEvolutionEvaluator"))
    #expect(cliSource.contains("private struct CLIEvolutionRegressionEvaluator"))
    #expect(cliSource.contains("private func runKuyuRegression"))
    #expect(!cliSource.contains("@MainActor\nprivate final class CLIEvolutionRegressionEvaluator"))
    #expect(!cliSource.contains("@MainActor\nprivate func runKuyuRegression"))
    #expect(cliSource.contains("runRegressionEnvironmentReadiness"))
    #expect(cliSource.contains("EvolutionVariationChoice"))
    #expect(cliSource.contains("EvolutionEvaluationChoice"))
    #expect(cliSource.contains("EvolutionSearchStrategyChoice"))
    #expect(cliSource.contains("EvolutionBootstrapSourceChoice"))
    #expect(cliSource.contains("EvolutionWorldModelUsageChoice"))
    #expect(cliSource.contains("candidateEvaluationConcurrency"))
    #expect(cliSource.contains("--mutation-noise-scale"))
    #expect(cliSource.contains("customLong(\"search-strategy\")"))
    #expect(cliSource.contains("customLong(\"antithetic-sampling\")"))
    #expect(cliSource.contains("customLong(\"adaptive-mutation\")"))
    #expect(cliSource.contains("customLong(\"common-random-seed\")"))
    #expect(cliSource.contains("printEvolutionSearchSummary"))
    #expect(cliSource.contains("bestVsIncumbentDelta"))
    #expect(cliSource.contains("acceptedCheckpoint="))
    #expect(cliSource.contains("if !artifacts.acceptedCheckpoint.accepted"))
    #expect(cliSource.contains("bestCandidate="))
    #expect(cliSource.contains("publishReasons="))
    #expect(cliSource.contains("EvolutionAcceptedCheckpointDecision.fileName"))
    #expect(cliSource.contains("minimumIncumbentImprovement"))
    #expect(cliSource.contains("minimumImprovementOverIncumbent: minimumIncumbentImprovement"))
    #expect(cliSource.contains("minimumNoveltyScore"))
    #expect(cliSource.contains("minimumNoveltyScore: minimumNoveltyScore"))
    #expect(cliSource.contains("qdCells="))
    #expect(cliSource.contains("finalMutationRate="))
    #expect(cliSource.contains("EvolutionQualityDiversityArchive.fileName"))
    #expect(cliSource.contains("no-crossover"))
    #expect(cliSource.contains("checkEvolutionInputs"))
    #expect(cliSource.contains("requiresMLXCheckpoint"))
    #expect(cliSource.contains("0..<episodes"))
    #expect(cliSource.contains("baseDefinitions[index % baseDefinitions.count]"))
    #expect(!orchestrator.contains("mutate"))
    #expect(!orchestrator.contains("crossover"))
}

@Test func xcodeE2EScriptUsesXcodeBuiltBinaryForMLXHarness() throws {
    let script = try readSource("scripts/check-xcode-e2e.sh")
    let readme = try readSource("README.md")

    #expect(script.contains("xcodebuild test"))
    #expect(script.contains("-derivedDataPath"))
    #expect(script.contains("Build/Products/$CONFIGURATION/kuyu"))
    #expect(script.contains("check-kuyu-regression"))
    #expect(script.contains("evolve-manas"))
    #expect(script.contains("accepted-checkpoint.json"))
    #expect(script.contains("evaluation-trace.jsonl"))
    #expect(script.contains("activeEvaluationCountAtStart"))
    #expect(!script.contains("swift run kuyu"))
    #expect(readme.contains("./scripts/check-xcode-e2e.sh"))
    #expect(readme.contains("Xcode is the authority for MLX and Metal-backed execution"))
}

@Test func learningReadinessScriptPreflightsExpensiveCampaignInputs() throws {
    let script = try readSource("scripts/check-learning-readiness.sh")
    let readme = try readSource("README.md")

    #expect(script.contains("KUYU_LEARNING_MIN_FREE_GB"))
    #expect(script.contains("xcodebuild build"))
    #expect(script.contains("check-kuyu-regression"))
    #expect(script.contains("teacherBaseline"))
    #expect(script.contains("bootstrap_train_args=("))
    #expect(script.contains("run_kuyu_plain \"${bootstrap_train_args[@]}\""))
    #expect(script.contains("DEFAULT_BOOTSTRAP_EPISODES=13"))
    #expect(script.contains("DEFAULT_BOOTSTRAP_EPOCHS=3"))
    #expect(script.contains("DEFAULT_BOOTSTRAP_MAX_BATCHES=32"))
    #expect(script.contains("BOOTSTRAP_LR=\"${KUYU_LEARNING_BOOTSTRAP_LR:-0.0001}\""))
    #expect(script.contains("BOOTSTRAP_MLX_SEED=\"${KUYU_LEARNING_BOOTSTRAP_MLX_SEED:-$([[ \"$TASK\" == \"singleLift\" ]] && printf \"11\" || printf \"\")}\""))
    #expect(script.contains("BOOTSTRAP_BIAS_DELTAS=\"${KUYU_LEARNING_BOOTSTRAP_BIAS_DELTAS:-$([[ \"$TASK\" == \"singleLift\" ]] && printf -- \"-0.016,-0.0152,-0.0148,-0.01465,-0.0146,-0.01455,-0.0145,-0.0144,-0.0143,-0.0142,-0.0140,-0.0138,-0.0132,-0.0125,-0.0115,-0.0105,-0.0095,-0.0085,-0.0075,-0.0065\" || printf \"\")}\""))
    #expect(script.contains("select-manas-bias-calibration"))
    #expect(script.contains("bias-calibration-selection.json"))
    #expect(script.contains("\"--deltas=$BOOTSTRAP_BIAS_DELTAS\""))
    #expect(script.contains("strict_checkpoint_passes()"))
    #expect(script.contains("BOOTSTRAP_STRICT_READY=1"))
    #expect(script.contains("bootstrap_rollout_args=("))
    #expect(script.contains("run_kuyu_with_model \"${bootstrap_rollout_args[@]}\""))
    #expect(script.contains("KUYU_LEARNING_REQUIRE_SOURCE_POLICY_PASS"))
    #expect(script.contains("DEFAULT_REQUIRE_SOURCE_POLICY_PASS=1"))
    #expect(script.contains("checkpoint_evaluation_args+=(--require-policy-pass)"))
    #expect(script.contains("--require-policy-pass"))
    #expect(script.contains("source checkpoint regression did not pass readiness"))
    #expect(script.contains("verify_ready_checkpoint_regression()"))
    #expect(script.contains("ready-regression"))
    #expect(script.contains("ready checkpoint regression did not pass readiness"))
    #expect(script.contains("ready=false"))
    #expect(script.contains("failureReasons"))
    #expect(script.contains("checkpoint-evaluation-task-quality-failed"))
    #expect(script.contains("learning-readiness-summary.json"))
    #expect(script.contains("source-regression"))
    #expect(script.contains("ready checkpoint missing file"))
    #expect(!script.contains("policyPassed"))
    #expect(!script.contains("evolve-manas"))
    #expect(!script.contains("swift run kuyu"))
    #expect(readme.contains("./scripts/check-learning-readiness.sh"))
    #expect(readme.contains("low-cost gate"))
}

@Test func rolloutRegressionUsesSingleLiftRuntimeParameterTuning() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let checkpointEvaluatorSource = try readSource("Sources/KuyuMLX/ManasMLXCheckpointEvaluator.swift")

    #expect(cliSource.contains("hoverThrustScale: hoverScale"))
    #expect(cliSource.contains("KuyuSingleLiftParameterTuning.tuned"))
    #expect(checkpointEvaluatorSource.contains("tunedParametersIfNeeded"))
    #expect(checkpointEvaluatorSource.contains("KuyuSingleLiftParameterTuning.tuned"))
    #expect(!cliSource.contains("maxThrust: 12.0"))
}

@Test func xcodeLearningCampaignScriptPersistsMultiSeedCheckpointProgression() throws {
    let script = try readSource("scripts/run-xcode-learning-campaign.sh")
    let validator = try readSource("scripts/validate-learning-campaign-artifacts.sh")
    let swiftValidator = try readSource("Sources/KuyuMLX/LearningCampaignArtifactValidator.swift")
    let orchestrator = try readSource("Sources/KuyuMLX/LearningCampaignOrchestrator.swift")
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let validateCommand = try readSource("Sources/KuyuCLI/ValidateLearningCampaign.swift")
    let readme = try readSource("README.md")

    #expect(script.contains("xcodebuild build"))
    #expect(script.contains("run-learning-campaign"))
    #expect(script.contains("KUYU_LEARNING_SEED_COUNT"))
    #expect(script.contains("KUYU_LEARNING_SEEDS"))
    #expect(script.contains("--seed-count"))
    #expect(script.contains("KUYU_LEARNING_SEEDS and KUYU_LEARNING_SEED_COUNT cannot both be set"))
    #expect(script.contains("KUYU_LEARNING_NO_QUALITY_GATE is not allowed for learning campaigns"))
    #expect(script.contains("KUYU_LEARNING_GENERATIONS"))
    #expect(script.contains("KUYU_LEARNING_POPULATION"))
    #expect(script.contains("KUYU_LEARNING_SOURCE_CHECKPOINT"))
    #expect(script.contains("KUYU_LEARNING_LOCK_PATH"))
    #expect(script.contains("KUYU_LEARNING_RESUME"))
    #expect(script.contains("another campaign is running"))
    #expect(script.contains("resume is owned by Swift artifacts"))
    #expect(script.contains("validate-learning-campaign --artifact-root"))
    #expect(script.contains("refusing to reuse non-empty artifact root"))
    #expect(script.contains("KUYU_LEARNING_MIN_FREE_GB"))
    #expect(script.contains("incomplete source checkpoint"))
    #expect(!script.contains("train-manas-core"))
    #expect(!script.contains("--export-dataset"))
    #expect(!script.contains("shutil.copytree"))
    #expect(!script.contains("swift run kuyu"))
    #expect(orchestrator.contains("learning-campaign-summary.json"))
    #expect(orchestrator.contains("learning-campaign-plan.json"))
    #expect(orchestrator.contains("learning-campaign-environment.json"))
    #expect(orchestrator.contains("campaign-status.json"))
    #expect(orchestrator.contains("progress.jsonl"))
    #expect(orchestrator.contains("resource-samples.jsonl"))
    #expect(orchestrator.contains("campaign-finished"))
    #expect(orchestrator.contains("acceptedCheckpoint.accepted"))
    #expect(orchestrator.contains("LearningCampaignCheckpointRegressionChecking"))
    #expect(orchestrator.contains("checkpoint-regressions"))
    #expect(orchestrator.contains("parentCheckpointRegressionRejected"))
    #expect(cliSource.contains("CLILearningCampaignCheckpointRegressionChecker"))
    #expect(cliSource.contains("EvolutionRunArtifactValidator().loadAndValidate"))
    #expect(orchestrator.contains("evaluationTraceCount"))
    #expect(orchestrator.contains("overlappedEvaluation"))
    #expect(orchestrator.contains("incumbentFitness"))
    #expect(orchestrator.contains("bestFitness"))
    #expect(orchestrator.contains("bestTaskPassRate"))
    #expect(orchestrator.contains("bestHoldTimeRatio"))
    #expect(readme.contains("./scripts/run-xcode-learning-campaign.sh"))
    #expect(readme.contains("multiple seeds, multiple generations, persistent checkpoints"))
    #expect(readme.contains("KUYU_LEARNING_SEED_COUNT=3"))
    #expect(readme.contains("task-specific source checkpoint"))
    #expect(readme.contains("learning-campaign-plan.json"))
    #expect(readme.contains("learning-campaign-environment.json"))
    #expect(readme.contains("campaign-status.json"))
    #expect(readme.contains("progress.jsonl"))
    #expect(readme.contains("resource-samples.jsonl"))
    #expect(readme.contains("resume is intentionally disabled"))
    #expect(readme.contains("./scripts/validate-learning-campaign-artifacts.sh"))
    #expect(readme.contains("kuyu validate-learning-campaign"))
    #expect(readme.contains("post-run artifact gate"))
    #expect(readme.contains("single-flight campaign lock"))
    #expect(readme.contains("refuses to reuse a non-empty artifact root"))
    #expect(validator.contains("validate-learning-campaign"))
    #expect(validator.contains("swift run kuyu"))
    #expect(validator.contains("KUYU_VALIDATE_ALLOW_FAILED"))
    #expect(swiftValidator.contains("public struct LearningCampaignArtifactValidator"))
    #expect(swiftValidator.contains("EvolutionRunArtifactValidator"))
    #expect(swiftValidator.contains("learning-campaign-validation.json"))
    #expect(swiftValidator.contains("missing-seed-evolution-artifact"))
    #expect(swiftValidator.contains("fitness-count-mismatch"))
    #expect(swiftValidator.contains("incomplete-final-checkpoint"))
    #expect(swiftValidator.contains("missing-parent-task-regression"))
    #expect(swiftValidator.contains("parent-task-regression-failed"))
    #expect(validateCommand.contains("struct ValidateLearningCampaign"))
    #expect(validateCommand.contains("LearningCampaignArtifactValidator"))
    #expect(validateCommand.contains("commandName: \"validate-learning-campaign\""))
    #expect(validateCommand.contains("allowRunning"))
}

private func readSource(_ relativePath: String) throws -> String {
    let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
    let url = root.appendingPathComponent(relativePath)
    return try String(contentsOf: url, encoding: .utf8)
}

private func readTrainingSource(_ relativePath: String) throws -> String {
    let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("kuyu-training", isDirectory: true)
    let url = root.appendingPathComponent(relativePath)
    return try String(contentsOf: url, encoding: .utf8)
}
