import Foundation
import Testing

@Test func simulationViewModelDoesNotOwnTrainingLoopController() throws {
    let source = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")

    #expect(!source.contains("TrainingLoopController("))
    #expect(!source.contains("trainingLoopController"))
}

@Test func configurationViewDoesNotBindDescriptorPathDirectly() throws {
    let source = try readSource("Sources/KuyuUI/Views/SimulationConfigurationView.swift")

    #expect(!source.contains("$model.modelDescriptorPath"))
    #expect(source.contains("setModelDescriptorPath("))
}

@Test func commandSystemOwnsTrainingLoopExecutionBoundary() throws {
    let source = try readSource("Sources/KuyuUI/Services/CommandSystem.swift")
    let trainingService = try readSource("Sources/KuyuUI/Services/TrainingService.swift")

    #expect(source.contains("TrainingLoopController(commandExecutor: self)"))
    #expect(source.contains("extension CommandSystem: TrainingLoopCommandExecuting"))
    #expect(source.contains("TrainingRunOrchestrator("))
    #expect(source.contains("ManasMLXTrainingBackendFactory().makeWorkerLocalBackend"))
    #expect(source.contains("sourceSnapshot: backendBundle.sourceSnapshot"))
    #expect(source.contains("extension CommandSystem: TrainingScenarioExecuting"))
    #expect(source.contains("runSuiteForTrainingRun"))
    #expect(trainingService.contains("ManasMLXTrainingRuntime"))
    #expect(trainingService.contains("TrainingBackendRequest("))
    #expect(!trainingService.contains(".trainCore("))
}

@Test func trainingLoopControllerDelegatesToSharedOrchestratorContract() throws {
    let source = try readSource("Sources/KuyuUI/Services/TrainingLoopController.swift")
    let adapterSource = try readSource("Sources/KuyuUI/Services/TrainingLoopEventAdapter.swift")
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")

    #expect(source.contains("runTrainingRunForTrainingLoop"))
    #expect(source.contains("TrainingRunConfig("))
    #expect(source.contains("TrainingLoopEventAdapter.present"))
    #expect(source.contains("TrainingLoopEventAdapter.presentCompletion"))
    #expect(adapterSource.contains("TrainingRunEvent"))
    #expect(adapterSource.contains("TrainingLoopSummary("))
    #expect(!source.contains("exportDatasetForTrainingLoop"))
    #expect(!source.contains("trainCoreForTrainingLoop"))
    #expect(cliSource.contains("TrainingRunOrchestrator("))
    #expect(cliSource.contains("ProbeManas.self"))
    #expect(cliSource.contains("TrainingProbeOrchestrator("))
    #expect(cliSource.contains("KuyuScenarioRuntime("))
    #expect(!cliSource.contains("probe-manas currently supports attitude only"))
    #expect(cliSource.contains("let scenarioStore = ManasMLXModelStore()"))
    #expect(cliSource.contains("let workerStore = ManasMLXModelStore()"))
    #expect(cliSource.contains("CLIScenarioExecutor("))
}

@Test func trainingDashboardDisplaysLearningCampaignArtifacts() throws {
    let dashboardSource = try readSource("Sources/KuyuUI/Views/TrainingDashboardView.swift")
    let configSource = try readSource("Sources/KuyuUI/Views/TrainingConfigurationView.swift")
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")

    #expect(dashboardSource.contains("LearningCampaignView(model: model)"))
    #expect(dashboardSource.contains("learningCampaignState"))
    #expect(dashboardSource.contains("startLearningCampaign()"))
    #expect(configSource.contains("Learning Campaign"))
    #expect(configSource.contains("startLearningCampaignMonitoring"))
    #expect(configSource.contains("useCurrentBestLearningCheckpoint"))
    #expect(viewModelSource.contains("LearningCampaignRunStore"))
    #expect(viewModelSource.contains("useCurrentLearningCampaignArtifactRoot"))
    #expect(viewModelSource.contains("commandSystem.startLearningCampaign"))
    #expect(viewModelSource.contains("ensureDescriptorForTask(reason: \"learningCampaignConfig\")"))
    #expect(dashboardSource.contains("learningCampaignProgressFraction"))
    #expect(dashboardSource.contains("learningCampaignCurrentPhase"))
    #expect(dashboardSource.contains("Failure Diagnostics"))
    #expect(dashboardSource.contains("CopyableTextBlockView"))
    #expect(!viewModelSource.contains("LearningCampaignProcessLauncher"))
}

@Test func logsAndFailureDiagnosticsStayOutOfInspector() throws {
    let logSummarySource = try readSource("Sources/KuyuUI/Views/LogSummaryView.swift")
    let runInspectorSource = try readSource("Sources/KuyuUI/Views/RunInspectorView.swift")
    let copyableSource = try readSource("Sources/KuyuUI/Views/CopyableTextBlockView.swift")
    let dashboardWorkspaceSource = try readSource("Sources/KuyuUI/Views/DashboardWorkspaceView.swift")
    let runStoreSource = try readSource("Sources/KuyuUI/Services/LearningCampaignRunStore.swift")

    #expect(copyableSource.contains("NSPasteboard.general"))
    #expect(copyableSource.contains(".textSelection(.enabled)"))
    #expect(copyableSource.contains("Button(\"Copy\")"))
    #expect(logSummarySource.contains("Recent Log Copy"))
    #expect(logSummarySource.contains(".textSelection(.enabled)"))
    #expect(dashboardWorkspaceSource.contains("RunsAndLogsDetailTab"))
    #expect(dashboardWorkspaceSource.contains("case .diagnostics"))
    #expect(dashboardWorkspaceSource.contains("CampaignDiagnosticsView"))
    #expect(dashboardWorkspaceSource.contains("CopyableTextBlockView"))
    #expect(dashboardWorkspaceSource.contains("diagnosticText"))
    #expect(dashboardWorkspaceSource.contains("case .logs"))
    #expect(dashboardWorkspaceSource.contains("LogSummaryView(model: model)"))
    #expect(dashboardWorkspaceSource.contains("case .artifacts"))
    #expect(dashboardWorkspaceSource.contains("TrainingArtifactsView(model: model)"))
    #expect(runInspectorSource.contains("Run State"))
    #expect(runInspectorSource.contains("Primary Issue"))
    #expect(!runInspectorSource.contains("CopyableTextBlockView"))
    #expect(!runInspectorSource.contains("Diagnostics"))
    #expect(!runInspectorSource.contains("No notes."))
    #expect(runStoreSource.contains("primaryFailureReason"))
    #expect(runStoreSource.contains("diagnosticText"))
    #expect(runStoreSource.contains("validation:"))
}

@Test func serviceDescriptorFailureLogsCarryRequiredMetadataKeys() throws {
    let source = try readSource("Sources/KuyuUI/Services/SimulationRunnerService.swift")

    #expect(source.contains("\"action\": \"descriptorLoadFailed\""))
    #expect(source.contains("\"modelDescriptor\""))
    #expect(source.contains("\"reason\": \"loadFailed\""))
    #expect(source.contains("\"error\""))
}

@Test func simulationViewModelDelegatesDescriptorAndTelemetryProjection() throws {
    let source = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let coordinatorSource = try readSource("Sources/KuyuUI/Services/TrainingRunCoordinator.swift")
    let bootstrapSource = try readSource("Sources/KuyuUI/Services/TrainingBootstrapCoordinator.swift")

    #expect(source.contains("DescriptorSelection.resolveForTask"))
    #expect(source.contains("telemetryPresenter.present"))
    #expect(source.contains("descendingIntentResolver.resolve"))
    #expect(source.contains("trainingRunPresenter.runCompleted"))
    #expect(source.contains("checkpointStore.persist"))
    #expect(source.contains("trainingRunCoordinator.prepare"))
    #expect(source.contains("trainingBootstrapCoordinator.makeRequest"))
    #expect(coordinatorSource.contains("TrainingRunPreparationInput"))
    #expect(coordinatorSource.contains("TrainingLoopConfig("))
    #expect(coordinatorSource.contains("SimulationRunRequest("))
    #expect(bootstrapSource.contains("TrainingBootstrapInput"))
    #expect(bootstrapSource.contains("TrainingRequest("))
    #expect(!source.contains("metadata[\"u_out_thrust\"]"))
    #expect(!source.contains("metadata[\"netAccelZ\"]"))
    #expect(!source.contains("private func parseDescending"))
    #expect(!source.contains("ScenarioMetricsBuilder.build"))
    #expect(!source.contains("modelStore.saveModel("))
}

@Test func trainingRunStoreIsArtifactDriven() throws {
    let source = try readSource("Sources/KuyuUI/Services/TrainingRunStore.swift")
    let controllerSource = try readSource("Sources/KuyuUI/Services/TrainingLoopController.swift")
    let adapterSource = try readSource("Sources/KuyuUI/Services/TrainingLoopEventAdapter.swift")
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let validatorSource = try readTrainingSource("Sources/KuyuTraining/TrainingRunArtifactValidator.swift")
    let artifactSource = try readTrainingSource("Sources/KuyuTraining/TrainingArtifacts.swift")

    #expect(source.contains("TrainingRunArtifactValidator"))
    #expect(source.contains("TrainingMetricRecord"))
    #expect(source.contains(".validationLoss"))
    #expect(source.contains(".passRate"))
    #expect(source.contains(".failureRate"))
    #expect(source.contains(".safetyViolation"))
    #expect(source.contains(".rewardAverage"))
    #expect(source.contains(".workerThroughput"))
    #expect(artifactSource.contains("artifact-contract.json"))
    #expect(validatorSource.contains("manifest.json"))
    #expect(validatorSource.contains("metrics.jsonl"))
    #expect(validatorSource.contains("convergence.json"))
    #expect(validatorSource.contains("checkpoint-decision.json"))
    #expect(controllerSource.contains("TrainingLoopEventAdapter.presentCompletion"))
    #expect(adapterSource.contains("artifactDirectory: artifactDirectory"))
    #expect(adapterSource.contains("checkpointDecision: result.checkpointDecision"))
    #expect(viewModelSource.contains("trainingRunStore.load"))
    #expect(viewModelSource.contains("lastConvergenceSummary"))
    #expect(viewModelSource.contains("lastCheckpointDecision"))
}

@Test func trainingDashboardShowsLiveLearningHealthAndGateState() throws {
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let dashboardSource = try readSource("Sources/KuyuUI/Views/TrainingDashboardView.swift")
    let studioSource = try readSource("Sources/KuyuUI/Views/LearningStudioDashboardView.swift")
    let simulationPreviewSource = try readSource("Sources/KuyuUI/Views/KuyuSimulationPreviewView.swift")
    let lineageSource = try readSource("Sources/KuyuUI/Views/PolicyLineageGraphView.swift")
    let liveStatusSource = try readSource("Sources/KuyuUI/Model/TrainingLiveStatus.swift")

    #expect(liveStatusSource.contains("struct TrainingLiveStatus"))
    #expect(viewModelSource.contains("trainingLiveStatus"))
    #expect(viewModelSource.contains("trainingTimeline"))
    #expect(viewModelSource.contains("updateRunQualityStatus"))
    #expect(viewModelSource.contains("passRateSamples"))
    #expect(viewModelSource.contains("safetyViolationSamples"))
    #expect(viewModelSource.contains("workerThroughputSamples"))
    #expect(dashboardSource.contains("LearningStudioDashboardView"))
    #expect(studioSource.contains("LearningStudioHeaderView"))
    #expect(studioSource.contains("LearningMetricChartView"))
    #expect(studioSource.contains("EvolutionFitnessChartView"))
    #expect(studioSource.contains("PolicyLineageGraphView"))
    #expect(studioSource.contains("KuyuSimulationPreviewView"))
    #expect(studioSource.contains("LearningExperimentListView"))
    #expect(studioSource.contains("LearningHyperparameterSettingsView"))
    #expect(simulationPreviewSource.contains("8ch observation"))
    #expect(simulationPreviewSource.contains("\"alt\""))
    #expect(lineageSource.contains("Policy Lineage"))
    #expect(viewModelSource.contains("RegressionRunStore"))
    #expect(viewModelSource.contains("lastPostRegressionGate"))
    #expect(dashboardSource.contains("Pass Rate"))
    #expect(dashboardSource.contains("Safety Violation"))
    #expect(dashboardSource.contains("Worker Throughput"))
}

@Test func boundedNavigationUsesWorkspaceAndWindowSections() throws {
    let appModelSource = try readSource("Sources/KuyuUI/Model/AppViewModel.swift")
    let workspaceSource = try readSource("Sources/KuyuUI/Model/BoundedWorkspace.swift")
    let sidebarSource = try readSource("Sources/KuyuUI/Views/BoundedSidebarView.swift")
    let systemStatusSource = try readSource("Sources/KuyuUI/Views/SystemStatusSummaryView.swift")

    #expect(appModelSource.contains("selectedWorkspace"))
    #expect(appModelSource.contains("selectedTrainingPhase"))
    #expect(workspaceSource.contains("case training"))
    #expect(workspaceSource.contains("case dashboard"))
    #expect(workspaceSource.contains("case experimentDesign"))
    #expect(workspaceSource.contains("case reinforcementLearning"))
    #expect(workspaceSource.contains("case geneticLearning"))
    #expect(workspaceSource.contains("case hybridIntegration"))
    #expect(workspaceSource.contains("case environment"))
    #expect(workspaceSource.contains("case analysis"))
    #expect(workspaceSource.contains("case report"))
    #expect(workspaceSource.contains("case monitor"))
    #expect(workspaceSource.contains("case settings"))
    #expect(workspaceSource.contains("case system"))
    #expect(sidebarSource.contains("List(selection: $model.selectedWorkspace)"))
    #expect(sidebarSource.contains("Section(\"実行\")"))
    #expect(sidebarSource.contains("Section(\"トレーニング\")"))
    #expect(sidebarSource.contains("Section(\"開く\")"))
    #expect(sidebarSource.contains("workspaceRow(.dashboard)"))
    #expect(sidebarSource.contains("workspaceRow(.experimentDesign)"))
    #expect(sidebarSource.contains("workspaceRow(.reinforcementLearning)"))
    #expect(sidebarSource.contains("workspaceRow(.geneticLearning)"))
    #expect(sidebarSource.contains("workspaceRow(.hybridIntegration)"))
    #expect(sidebarSource.contains("workspaceRow(.environment)"))
    #expect(!sidebarSource.contains("workspaceRow(.analysis)"))
    #expect(!sidebarSource.contains("workspaceRow(.report)"))
    #expect(!sidebarSource.contains("workspaceRow(.monitor)"))
    #expect(!sidebarSource.contains("workspaceRow(.settings)"))
    #expect(!sidebarSource.contains("workspaceRow(.system)"))
    #expect(!sidebarSource.contains("SidebarBottomManagementView"))
    #expect(sidebarSource.contains(".safeAreaInset(edge: .bottom"))
    #expect(sidebarSource.contains("model.selectedWorkspace = .settings"))
    #expect(sidebarSource.contains("model.selectedWorkspace = .system"))
    #expect(sidebarSource.contains("SystemStatusSummaryView(model: model.simulationViewModel)"))
    #expect(sidebarSource.contains("openWindow(id: windowID.rawValue)"))
    #expect(sidebarSource.contains("windowButton(.simulation)"))
    #expect(sidebarSource.contains("windowButton(.monitor)"))
    #expect(sidebarSource.contains("windowButton(.analysis)"))
    #expect(sidebarSource.contains("windowButton(.report)"))
    #expect(sidebarSource.contains(".tag(workspace)"))
    #expect(systemStatusSource.contains("GroupBox(\"システムステータス\")"))
    #expect(systemStatusSource.contains("LabeledContent(\"Run\""))
    #expect(systemStatusSource.contains("LabeledContent(\"Readiness\""))
    #expect(systemStatusSource.contains("LabeledContent(\"Monitor\""))
    #expect(!systemStatusSource.contains("StatusPill"))
    #expect(!systemStatusSource.contains("RoundedRectangle"))
    #expect(systemStatusSource.contains("システムステータス"))
    #expect(systemStatusSource.contains("learningCampaignReadiness.status.label"))
    #expect(systemStatusSource.contains("learningCampaignCurrentPhase"))
    #expect(systemStatusSource.contains("learningCampaignMonitorEnabled"))
    #expect(systemStatusSource.contains("MTLCreateSystemDefaultDevice"))
    #expect(systemStatusSource.contains("ProcessInfo.processInfo.physicalMemory"))
    #expect(systemStatusSource.contains("volumeAvailableCapacityForImportantUsage"))
}

@Test func boundedToolbarUsesSymbolOnlyTrainingControlsAndStatusChips() throws {
    let toolbarSource = try readSource("Sources/KuyuUI/Views/BoundedToolbarContent.swift")
    let contentSource = try readSource("Sources/KuyuUI/Views/ContentView.swift")
    let boundedInspectorSource = try readSource("Sources/KuyuUI/Views/BoundedInspectorView.swift")
    let chipsSource = try readSource("Sources/KuyuUI/Views/BoundedRunStatusChipsView.swift")
    let simulationWindowSource = try readSource("Sources/KuyuUI/Views/SimulationWindowContentView.swift")
    let reportWindowSource = try readSource("Sources/KuyuUI/Views/ReportWindowContentView.swift")
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let appViewModelSource = try readSource("Sources/KuyuUI/Model/AppViewModel.swift")
    let monitorWindowSource = try readSource("Sources/KuyuUI/Views/MonitorWindowContentView.swift")
    let robotPoseSource = try readSource("Sources/KuyuUI/Views/RobotPoseSnapshot.swift")

    #expect(toolbarSource.contains("Image(systemName: \"play.fill\")"))
    #expect(toolbarSource.contains("Image(systemName: \"pause.fill\")"))
    #expect(toolbarSource.contains("Image(systemName: \"stop.fill\")"))
    #expect(toolbarSource.contains("Image(systemName: \"arrow.counterclockwise\")"))
    #expect(toolbarSource.contains("Image(systemName: \"forward.end.fill\")"))
    #expect(toolbarSource.contains("openWindow(id: BoundedWindowID.report.rawValue)"))
    #expect(toolbarSource.contains("resetSimulationPlayback()"))
    #expect(toolbarSource.contains("stepSimulationPlayback()"))
    #expect(simulationWindowSource.contains("$model.simulationPlaybackFraction"))
    #expect(simulationWindowSource.contains("$model.simulationShowsTrajectoryOverlay"))
    #expect(simulationWindowSource.contains("$model.simulationShowsSensorReadouts"))
    #expect(simulationWindowSource.contains("$model.simulationShowsRewardEvents"))
    #expect(toolbarSource.contains("ReportExportMenu"))
    #expect(toolbarSource.contains("ReportExportFormat.allCases"))
    #expect(toolbarSource.contains("exportLearningReport(format: format)"))
    #expect(toolbarSource.contains("reportExportStatus"))
    #expect(reportWindowSource.contains("KeyTrainingChartsView(model: model)"))
    #expect(!reportWindowSource.contains("not connected"))
    #expect(viewModelSource.contains("func stepSimulationPlayback"))
    #expect(viewModelSource.contains("func exportLearningReport(format: ReportExportFormat)"))
    #expect(appViewModelSource.contains("applySelectedEnvironment()"))
    #expect(appViewModelSource.contains("availableProjectNames"))
    #expect(appViewModelSource.contains("simulationViewModel.taskMode = .lift"))
    #expect(appViewModelSource.contains("simulationViewModel.taskMode = .singleLift"))
    #expect(monitorWindowSource.contains("MTLCreateSystemDefaultDevice"))
    #expect(monitorWindowSource.contains("ProcessInfo.processInfo"))
    #expect(robotPoseSource.contains("replaySnapshot(model: model)"))
    #expect(robotPoseSource.contains("simulationPlaybackFraction"))
    #expect(toolbarSource.contains("BoundedHeaderControlsView"))
    #expect(toolbarSource.contains("BoundedHeaderStatusView"))
    #expect(toolbarSource.contains("BoundedHeaderToolsMenu"))
    #expect(toolbarSource.contains("BoundedPrincipalToolbarView"))
    #expect(toolbarSource.contains("TrainingPhaseStepperView"))
    #expect(toolbarSource.contains(".pickerStyle(.segmented)"))
    #expect(toolbarSource.contains("isTrainingWorkspace"))
    #expect(toolbarSource.contains("$model.selectedTrainingPhase"))
    #expect(toolbarSource.contains("Menu {"))
    #expect(!toolbarSource.contains("private var projectControls"))
    #expect(!toolbarSource.contains("private var utilityControls"))
    #expect(toolbarSource.contains("ToolbarItemGroup(placement: .navigation)"))
    #expect(toolbarSource.contains("ToolbarItem(placement: .principal)"))
    #expect(toolbarSource.contains("ToolbarItemGroup(placement: .primaryAction)"))
    #expect(contentSource.contains(".inspector(isPresented: $showInspector)"))
    #expect(contentSource.contains("BoundedInspectorView(model: model)"))
    #expect(!contentSource.contains("model.selectedWorkspace == .dashboard"))
    #expect(boundedInspectorSource.contains("RunInspectorView(model: model)"))
    #expect(boundedInspectorSource.contains("LaunchValidationView(model: trainingModel)"))
    #expect(boundedInspectorSource.contains("case .settings"))
    #expect(boundedInspectorSource.contains("case .system"))
    #expect(toolbarSource.contains("Picker(\"Project\""))
    #expect(toolbarSource.contains("ForEach(model.availableProjectNames"))
    #expect(toolbarSource.contains("Picker(\"Environment\""))
    #expect(chipsSource.contains("世代"))
    #expect(chipsSource.contains("エピソード"))
    #expect(chipsSource.contains("平均報酬"))
    #expect(chipsSource.contains("最良適応度"))
}

@Test func boundedWorkspaceResponsibilitiesAreSeparated() throws {
    let dashboardSource = try readSource("Sources/KuyuUI/Views/DashboardWorkspaceView.swift")
    let trainingSource = try readSource("Sources/KuyuUI/Views/TrainingWorkspaceView.swift")
    let experimentSource = try readSource("Sources/KuyuUI/Views/ExperimentDesignView.swift")
    let launchSource = try readSource("Sources/KuyuUI/Views/LaunchValidationView.swift")
    let trainingPhaseSource = try readSource("Sources/KuyuUI/Model/BoundedTrainingPhase.swift")
    let strategySource = try readSource("Sources/KuyuUI/Model/LearningStrategySelection.swift")
    let inspectorSource = try readSource("Sources/KuyuUI/Views/RunInspectorView.swift")
    let boundedInspectorSource = try readSource("Sources/KuyuUI/Views/BoundedInspectorView.swift")
    let viewModelSource = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let commandSystemSource = try readSource("Sources/KuyuUI/Services/CommandSystem.swift")
    let runnerSource = try readSource("Sources/KuyuMLX/LearningCampaignRunner.swift")

    #expect(!dashboardSource.contains("CurrentRunSummaryView"))
    #expect(dashboardSource.contains("RunListView"))
    #expect(dashboardSource.contains("RunQueueView"))
    #expect(!dashboardSource.contains("CheckpointSummaryView"))
    #expect(dashboardSource.contains("LogSummaryView"))
    #expect(inspectorSource.contains("@Environment(\\.openWindow)"))
    #expect(inspectorSource.contains("openWindow(id: BoundedWindowID.simulation.rawValue)"))
    #expect(inspectorSource.contains("openWindow(id: BoundedWindowID.analysis.rawValue)"))
    #expect(inspectorSource.contains("openWindow(id: BoundedWindowID.report.rawValue)"))
    let toolbarSource = try readSource("Sources/KuyuUI/Views/BoundedToolbarContent.swift")
    #expect(trainingSource.contains("ExperimentDesignView"))
    #expect(trainingSource.contains("ReinforcementLearningConfigView"))
    #expect(trainingSource.contains("GeneticLearningConfigView"))
    #expect(trainingSource.contains("HybridIntegrationConfigView"))
    #expect(trainingSource.contains("EnvironmentConfigView"))
    #expect(toolbarSource.contains("TrainingPhaseStepperView"))
    #expect(!trainingSource.contains("TrainingPhaseStepperView"))
    #expect(trainingSource.contains("TrainingStrategyChoiceView"))
    #expect(!trainingSource.contains("TrainingExecutionPreviewView"))
    #expect(boundedInspectorSource.contains("Training Inspector"))
    #expect(boundedInspectorSource.contains("Runtime Summary"))
    #expect(trainingSource.contains("TrainingLaunchReviewView"))
    #expect(trainingSource.contains("TrainingPhaseNavigationView"))
    #expect(trainingSource.contains("model.selectLearningStrategy(strategy)"))
    #expect(trainingSource.contains("strategy.availabilityLabel"))
    #expect(strategySource.contains("var isExecutable"))
    #expect(strategySource.contains("case .hybrid:"))
    #expect(strategySource.contains("return true"))
    #expect(trainingSource.contains("learningStrategySelection"))
    #expect(trainingSource.contains("チェックリスト"))
    #expect(trainingSource.contains("受理ポリシー"))
    #expect(experimentSource.contains("$model.learningCampaignExperimentName"))
    #expect(experimentSource.contains("$model.learningCampaignExperimentDescription"))
    #expect(experimentSource.contains("$model.learningCampaignTagsText"))
    #expect(launchSource.contains("saveLearningCampaignTemplate()"))
    #expect(launchSource.contains("queueLearningCampaignRun()"))
    #expect(viewModelSource.contains("LearningCampaignTemplateDraft"))
    #expect(viewModelSource.contains("LearningCampaignQueuedRun"))
    #expect(viewModelSource.contains("saveLearningCampaignTemplate"))
    #expect(viewModelSource.contains("queueLearningCampaignRun"))
    #expect(viewModelSource.contains("func selectLearningStrategy"))
    #expect(viewModelSource.contains("guard learningStrategySelection.isExecutable else"))
    #expect(trainingPhaseSource.contains("case template"))
    #expect(trainingPhaseSource.contains("case environment"))
    #expect(trainingPhaseSource.contains("case strategy"))
    #expect(trainingPhaseSource.contains("case launch"))
    #expect(experimentSource.contains("Experiment Name"))
    #expect(launchSource.contains("Start New Run"))
    #expect(launchSource.contains("Dry Run Validation"))
    #expect(launchSource.contains("validateLearningCampaignLaunch()"))
    #expect(launchSource.contains("learningCampaignPreset"))
    #expect(launchSource.contains("estimateLearningCampaignCost()"))
    #expect(launchSource.contains("Regression Episodes"))
    #expect(viewModelSource.contains("LearningCampaignLaunchEstimate"))
    #expect(viewModelSource.contains("makeLearningCampaignLaunchEstimate"))
    #expect(viewModelSource.contains("candidateEvaluations"))
    #expect(viewModelSource.contains("regressionEpisodes"))
    #expect(viewModelSource.contains("makeLearningCampaignRunConfig"))
    #expect(viewModelSource.contains("tier: learningCampaignTier()"))
    #expect(viewModelSource.contains("cutPeriodSteps: cutPeriodSteps"))
    #expect(viewModelSource.contains("kp: kp"))
    #expect(viewModelSource.contains("hoverScale: hoverThrustScale"))
    #expect(commandSystemSource.contains("validateLearningCampaign(config: LearningCampaignRunConfig)"))
    #expect(runnerSource.contains("kp: config.kp"))
    #expect(runnerSource.contains("hoverScale: config.hoverScale"))
    #expect(!trainingSource.contains("RunListView"))
}

@Test func boundedAppRoutesAuxiliaryWorkspacesThroughSingleInstanceWindows() throws {
    let appSource = try readBoundedSource("Bounded/BoundedApp.swift")
    let windowIDSource = try readSource("Sources/KuyuUI/Model/BoundedWindowID.swift")
    let mainContentSource = try readSource("Sources/KuyuUI/Views/BoundedMainContentView.swift")

    #expect(windowIDSource.contains("case main"))
    #expect(windowIDSource.contains("case welcome"))
    #expect(windowIDSource.contains("case simulation"))
    #expect(windowIDSource.contains("case monitor"))
    #expect(windowIDSource.contains("case analysis"))
    #expect(windowIDSource.contains("case report"))
    #expect(appSource.contains("Window(BoundedWindowID.welcome.title"))
    #expect(appSource.contains("Window(BoundedWindowID.main.title"))
    #expect(appSource.contains("Window(BoundedWindowID.simulation.title"))
    #expect(appSource.contains("Window(BoundedWindowID.monitor.title"))
    #expect(appSource.contains("Window(BoundedWindowID.analysis.title"))
    #expect(appSource.contains("Window(BoundedWindowID.report.title"))
    #expect(!appSource.contains("WindowGroup(BoundedWindowID.main.title"))
    #expect(!appSource.contains("WindowGroup(BoundedWindowID.welcome.title"))
    #expect(appSource.contains("BoundedWelcomeWindowContentView"))
    #expect(appSource.contains("SimulationWindowContentView"))
    #expect(appSource.contains("MonitorWindowContentView"))
    #expect(appSource.contains("AnalysisWindowContentView"))
    #expect(appSource.contains("ReportWindowContentView"))
    #expect(mainContentSource.contains("case .analysis, .report, .monitor"))
    #expect(mainContentSource.contains("AuxiliaryWindowPlaceholderView"))
    #expect(!mainContentSource.contains("AnalysisWindowContentView(model: model.simulationViewModel)"))
    #expect(!mainContentSource.contains("ReportWindowContentView(model: model.simulationViewModel)"))
    #expect(!mainContentSource.contains("MonitorWindowContentView(model: model.simulationViewModel)"))
}

@Test func boundedUINewTypesAvoidPanelSuffix() throws {
    let viewSources = [
        "Sources/KuyuUI/Views/BoundedSidebarView.swift",
        "Sources/KuyuUI/Views/BoundedToolbarContent.swift",
        "Sources/KuyuUI/Views/DashboardWorkspaceView.swift",
        "Sources/KuyuUI/Views/TrainingWorkspaceView.swift",
        "Sources/KuyuUI/Views/SimulationWindowContentView.swift",
        "Sources/KuyuUI/Views/MonitorWindowContentView.swift",
        "Sources/KuyuUI/Views/AnalysisWindowContentView.swift",
        "Sources/KuyuUI/Views/ReportWindowContentView.swift"
    ]
    for sourcePath in viewSources {
        let source = try readSource(sourcePath)
        #expect(!source.contains("Panel"))
    }
}

@Test func cliHarnessUsesProbeSelectedCheckpointContract() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let probeSource = try readTrainingSource("Sources/KuyuTraining/TrainingProbeOrchestrator.swift")
    let validatorSource = try readTrainingSource("Sources/KuyuTraining/TrainingProbeArtifactValidator.swift")
    let regressionArtifactSource = try readSource("Sources/KuyuMLX/KuyuRegressionArtifacts.swift")

    #expect(probeSource.contains("selectedCheckpointRole"))
    #expect(probeSource.contains("sourceCheckpointURL"))
    #expect(probeSource.contains("selectedCheckpointURL"))
    #expect(validatorSource.contains("validateSelectedCheckpoint"))
    #expect(validatorSource.contains("candidate checkpoint cannot be selected when probe is rejected"))
    #expect(cliSource.contains("selectedCandidateCheckpointURL(result.comparison)"))
    #expect(cliSource.contains("sourceCheckpointURL(from: sourceCheckpointPath)"))
    #expect(cliSource.contains("repairSourceCheckpointURL(from: result)"))
    #expect(cliSource.contains("currentSourceCheckpointURL = repairSourceCheckpointURL"))
    #expect(cliSource.contains("result.training.checkpointDecision.candidateCheckpointURL"))
    #expect(cliSource.contains("TrainingHarnessGateReport"))
    #expect(regressionArtifactSource.contains("public struct KuyuRegressionGateReport"))
    #expect(cliSource.contains("gateReport: gateReport"))
    #expect(cliSource.contains("post-regression-failed"))
    #expect(cliSource.contains("post-regression-min-reward-average"))
    #expect(cliSource.contains("min-reward-average"))
    #expect(cliSource.contains("reward-average-below-min"))
    #expect(cliSource.contains("post-regression-reward-average-below-min"))
    #expect(cliSource.contains("postRegressionAcceptanceSatisfied(postRegression)"))
    #expect(cliSource.contains("postRegressionApplicable(regression)"))
    #expect(cliSource.contains("primaryRejectReason"))
    #expect(cliSource.contains("taskPassRate"))
    #expect(cliSource.contains("minimumHoldTimeRatio"))
    #expect(cliSource.contains("maximumAltitudeErrorRatio"))
    #expect(cliSource.contains("worstScenarioID"))
    #expect(!cliSource.contains("regression.rolloutSuites.first"))
    #expect(!cliSource.contains("firstEntry?.taskQuality.first"))
    #expect(cliSource.contains("tasks: [simulationTaskMode(from: task)]"))
    #expect(cliSource.contains("regressionRolloutTask(selectedTasks)"))
    #expect(cliSource.contains("makeRegressionRolloutDefinitions"))
    #expect(cliSource.contains("TaskEvaluationProfile.profile"))
    #expect(cliSource.contains("regressionProfile.motorNerveSettings"))
    #expect(!cliSource.contains("regressionMotorNerveSettings"))
    #expect(cliSource.contains("RunLearningCampaign.self"))
    #expect(cliSource.contains("commandName: \"run-learning-campaign\""))
    #expect(cliSource.contains("--source-checkpoint is required."))
    #expect(cliSource.contains("LearningCampaignRunner"))
    #expect(!cliSource.contains("suiteForDefinitions = regressionTask == .attitude ? suite : nil"))
    #expect(cliSource.contains("taskFailureCount == 0"))
    #expect(cliSource.contains("evaluateRegressionEpisodes("))
    #expect(cliSource.contains("selected-checkpoint-not-candidate"))
    #expect(cliSource.contains("teacher-divergence-regression"))
    #expect(!cliSource.contains("?? result.training.checkpointDecision.candidateCheckpointURL"))
}

@Test func cliRegressionGateRequiresTaskPassAndRewardQuality() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let artifactsSource = try readSource("Sources/KuyuMLX/KuyuRegressionArtifacts.swift")
    let qualityGateSource = try readSource("Sources/KuyuMLX/KuyuRegressionQualityGatePolicy.swift")
    let gateSource = try readSource("Sources/KuyuMLX/KuyuRegressionGatePolicy.swift")
    let validatorSource = try readSource("Sources/KuyuMLX/KuyuRegressionArtifactValidator.swift")

    #expect(cliSource.contains("KuyuRegressionGatePolicy.report"))
    #expect(cliSource.contains("CheckKuyuRegressionMatrix"))
    #expect(cliSource.contains("kuyu-regression-matrix-summary.json"))
    #expect(cliSource.contains("KuyuRegressionQualityGatePolicy.minimumRewardAverage"))
    #expect(qualityGateSource.contains("defaultMinimumRewardAverage(for task: String)"))
    #expect(qualityGateSource.contains("case \"lift\", \"singleLift\""))
    #expect(qualityGateSource.contains("override ?? defaultMinimumRewardAverage(for: task)"))
    #expect(qualityGateSource.contains("referenceEvaluatorID"))
    #expect(qualityGateSource.contains("TaskEvaluationProfile.profile(task: task)"))
    #expect(qualityGateSource.contains("minimumTaskPassRate: profile?.minimumTaskPassRate"))
    #expect(qualityGateSource.contains("liftThresholdSource: profile?.liftThresholdSource"))
    #expect(qualityGateSource.contains("scenario.liftEnvelope"))
    #expect(gateSource.contains("taskPassCount != entry.episodeCount"))
    #expect(gateSource.contains("task-pass-mismatch"))
    #expect(gateSource.contains("task-pass-rate-below-min"))
    #expect(gateSource.contains("entry.rewardAverage < minimumRewardAverage"))
    #expect(gateSource.contains("reward-average-below-min"))
    #expect(cliSource.contains("gateReport.accepted"))
    #expect(cliSource.contains("allPassed: gateReport.accepted"))
    #expect(artifactsSource.contains("qualityGateTask"))
    #expect(artifactsSource.contains("taskQuality"))
    #expect(artifactsSource.contains("KuyuRegressionQualityRequirement"))
    #expect(artifactsSource.contains("qualityEvaluatorID"))
    #expect(artifactsSource.contains("minimumHoldTimeRatio"))
    #expect(artifactsSource.contains("requiresReferenceTaskPass"))
    #expect(artifactsSource.contains("liftThresholdSource"))
    #expect(validatorSource.contains("public struct KuyuRegressionArtifactValidator"))
    #expect(validatorSource.contains("unsupportedSchemaVersion"))
    #expect(validatorSource.contains("gateReportMismatch"))
    #expect(validatorSource.contains("invalidTaskQualityCount"))
    #expect(validatorSource.contains("nonFiniteTaskQuality"))
    #expect(validatorSource.contains("rolloutPassedMismatch"))
    #expect(cliSource.contains("loadAndValidate(from: artifactRoot)"))
}

@Test func cliHarnessFeedsRecoveryDatasetsIntoLaterAttempts() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let trainingSource = try readTrainingSource("Sources/KuyuTraining/TrainingRunOrchestrator.swift")
    let singlePropRelabelerSource = try readTrainingSource("Sources/KuyuTraining/SinglePropRecoveryRelabeler.swift")
    let liftRelabelerSource = try readTrainingSource("Sources/KuyuTraining/LiftRecoveryRelabeler.swift")

    #expect(trainingSource.contains("additionalDatasetURLs"))
    #expect(trainingSource.contains("additionalDatasetRepeatCount"))
    #expect(trainingSource.contains("TrainingDatasetMixer().mix"))
    #expect(cliSource.contains("acceptedRecoveryDatasetURL(from: result)"))
    #expect(cliSource.contains("recoveryDatasetURLs.append(recoveryDatasetURL)"))
    #expect(cliSource.contains("additionalDatasetURLs: recoveryDatasetURLs"))
    #expect(cliSource.contains("additionalDatasetRepeatCount: recoveryRepeat"))
    #expect(cliSource.contains("--recovery-repeat"))
    #expect(cliSource.contains("includeOnlyFailedScenarios: !includeSuccessfulScenarios"))
    #expect(cliSource.contains("includeSuccessfulScenarios: Bool"))
    #expect(cliSource.contains("LiftRecoveryRelabeler()"))
    #expect(cliSource.contains("KuyLiftSuite().scenarios()"))
    #expect(cliSource.contains("SinglePropRecoveryRelabeler()"))
    #expect(cliSource.contains("KuySingleLiftSuite().scenarios()"))
    #expect(singlePropRelabelerSource.contains("SinglePropHoverCut"))
    #expect(liftRelabelerSource.contains("LiftRecoveryRelabelConfig"))
    #expect(liftRelabelerSource.contains("teacherDrives"))
    #expect(liftRelabelerSource.contains("DriveIntent(index: DriveIndex(3)"))
}

@Test func mlxDatasetLoadingIsDeterministicForHarnessMixing() throws {
    let mlxSource = try readSource("Sources/KuyuMLX/ManasMLXModelStore.swift")
    let trainingSource = try readTrainingSource("Sources/KuyuTraining/TrainingRunOrchestrator.swift")

    #expect(mlxSource.contains(".sorted { $0.lastPathComponent < $1.lastPathComponent }"))
    #expect(trainingSource.contains("sources: repeatedAdditionalDatasetURLs + [exportedDatasetDirectory]"))
}

@Test func simulationViewModelDelegatesLoopStateReduction() throws {
    let source = try readSource("Sources/KuyuUI/Model/SimulationViewModel.swift")
    let reducerSource = try readSource("Sources/KuyuUI/Services/TrainingLoopStateReducer.swift")

    #expect(source.contains("trainingLoopReducer.reduce"))
    #expect(source.contains("currentTrainingLoopState()"))
    #expect(source.contains("applyTrainingLoopState("))
    #expect(reducerSource.contains("struct TrainingLoopStateReducer"))
    #expect(reducerSource.contains("TrainingLoopStateSnapshot"))
    #expect(reducerSource.contains("case .completed"))
    #expect(!source.contains("loopStatusMessage = \"Iteration \\(iteration)\""))
}

@Test func snapshotBackendContractStaysOutsideMLXImplementation() throws {
    let contract = try readTrainingSource("Sources/KuyuTraining/TrainingBackendSnapshot.swift")
    let workerSnapshot = try readTrainingSource("Sources/KuyuTraining/WorkerSnapshot.swift")
    let workerPlan = try readTrainingSource("Sources/KuyuTraining/ParallelTrainingWorkerPlan.swift")
    let checkpointDecision = try readTrainingSource("Sources/KuyuTraining/CheckpointDecision.swift")
    let reinforcementContract = try readTrainingSource("Sources/KuyuTraining/ReinforcementTrainingBackend.swift")
    let learningRunTypes = try readTrainingSource("Sources/KuyuTraining/LearningRunTypes.swift")
    let orchestrator = try readTrainingSource("Sources/KuyuTraining/TrainingRunOrchestrator.swift")
    let mlxBackend = try readSource("Sources/KuyuMLX/ManasMLXTrainingBackend.swift")
    let mlxBackendFactory = try readSource("Sources/KuyuMLX/ManasMLXTrainingBackendFactory.swift")
    let mlxSnapshotProvider = try readSource("Sources/KuyuMLX/ManasMLXSnapshotProvider.swift")
    let mlxRuntime = try readSource("Sources/KuyuMLX/ManasMLXTrainingRuntime.swift")
    let loopController = try readSource("Sources/KuyuUI/Services/TrainingLoopController.swift")

    #expect(contract.contains("public protocol SnapshotTrainingBackend"))
    #expect(contract.contains("TrainingBackendSnapshot"))
    #expect(reinforcementContract.contains("public protocol ReinforcementTrainingBackend"))
    #expect(reinforcementContract.contains("ReinforcementTrainingWorkerMetric"))
    #expect(learningRunTypes.contains("workerIndex: Int?"))
    #expect(learningRunTypes.contains("snapshotID: String?"))
    #expect(learningRunTypes.contains("rolloutShardURL: URL?"))
    #expect(orchestrator.contains("workerMetricRecords"))
    #expect(loopController.contains("case reinforcementTrainingCompleted"))
    #expect(workerSnapshot.contains("public struct WorkerSnapshot"))
    #expect(workerSnapshot.contains("public protocol SnapshotProviding"))
    #expect(workerPlan.contains("public struct ParallelTrainingWorkerPlan"))
    #expect(workerPlan.contains("rolloutShardURL"))
    #expect(reinforcementContract.contains("workerPlan: ParallelTrainingWorkerPlan?"))
    #expect(checkpointDecision.contains("public struct CheckpointDecision"))
    #expect(checkpointDecision.contains("public struct CheckpointRepository"))
    #expect(mlxBackend.contains("SnapshotTrainingBackend"))
    #expect(mlxBackend.contains("ManasMLXTrainingRuntime"))
    #expect(mlxBackend.contains("checkpointDirectory(for: request)"))
    #expect(mlxBackendFactory.contains("let workerStore = ManasMLXModelStore()"))
    #expect(mlxBackendFactory.contains("candidate-checkpoints"))
    #expect(mlxBackendFactory.contains("source-checkpoint"))
    #expect(mlxSnapshotProvider.contains("SnapshotProviding"))
    #expect(mlxSnapshotProvider.contains("workerRootURL"))
    #expect(mlxSnapshotProvider.contains("copyItem"))
    #expect(!mlxBackend.contains("modelStore: ManasMLXModelStore"))
    #expect(!mlxBackend.contains(".trainCore("))
    #expect(mlxRuntime.contains(".trainCore("))
    #expect(mlxRuntime.contains("request.sourceSnapshot"))
    #expect(mlxRuntime.contains(".loadModel("))
}

@Test func evolutionContractKeepsKuyuAsHarnessAndMLXAsVariationBackend() throws {
    let runTypes = try readTrainingSource("Sources/KuyuTraining/EvolutionRunTypes.swift")
    let backendContract = try readTrainingSource("Sources/KuyuTraining/EvolutionBackend.swift")
    let orchestrator = try readTrainingSource("Sources/KuyuTraining/EvolutionRunOrchestrator.swift")
    let artifacts = try readTrainingSource("Sources/KuyuTraining/EvolutionArtifacts.swift")
    let validator = try readTrainingSource("Sources/KuyuTraining/EvolutionArtifactValidator.swift")
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let mlxEvolution = try readSource("Sources/KuyuMLX/ManasMLXEvolutionBackend.swift")

    #expect(runTypes.contains("public struct GenomeCandidate"))
    #expect(runTypes.contains("public struct FitnessSummary"))
    #expect(runTypes.contains("teacherDelta: Double?"))
    #expect(runTypes.contains("public enum EvolutionSearchStrategy"))
    #expect(runTypes.contains("case antitheticEvolutionStrategy"))
    #expect(runTypes.contains("case qualityDiversity"))
    #expect(runTypes.contains("public struct EvolutionAdaptiveMutationConfig"))
    #expect(runTypes.contains("behaviorDescriptor: [String: Double]"))
    #expect(runTypes.contains("antitheticPairID: String?"))
    #expect(runTypes.contains("commonRandomSeed: UInt64"))
    #expect(runTypes.contains("isIncumbent: Bool?"))
    #expect(backendContract.contains("public protocol EvolutionaryTrainingBackend"))
    #expect(backendContract.contains("public protocol EvolutionCandidateEvaluating"))
    #expect(backendContract.contains("mutationNoiseScale"))
    #expect(orchestrator.contains("EvolutionRunOrchestrator"))
    #expect(orchestrator.contains("backend.seedPopulation"))
    #expect(orchestrator.contains("backend.produceNextGeneration"))
    #expect(orchestrator.contains("EvolutionQualityDiversityArchiveBuilder"))
    #expect(orchestrator.contains("nextMutationSchedule"))
    #expect(artifacts.contains("evolution-manifest.json"))
    #expect(artifacts.contains("fitness.jsonl"))
    #expect(artifacts.contains("accepted-checkpoint.json"))
    #expect(artifacts.contains("quality-diversity-archive.json"))
    #expect(validator.contains("nonFiniteFitness"))
    #expect(validator.contains("lineageMismatch"))
    #expect(validator.contains("qualityDiversityCandidateMissing"))
    #expect(validator.contains("nonFiniteQualityDiversityCell"))
    #expect(mlxEvolution.contains("ManasMLXGenomeVariationProviding"))
    #expect(mlxEvolution.contains("ManasMLXGaussianMutationProvider"))
    #expect(mlxEvolution.contains("MLXRandom.normal"))
    #expect(mlxEvolution.contains("antitheticPairID"))
    #expect(mlxEvolution.contains("antitheticSign"))
    #expect(mlxEvolution.contains("parentCheckpointURLs"))
    #expect(mlxEvolution.contains("preserveIncumbent: true"))
    #expect(mlxEvolution.contains("candidatePreservesIncumbent ? 0 : mutationRate"))
    #expect(mlxEvolution.contains("isIncumbent: request.isIncumbent"))
    #expect(mlxEvolution.contains("ManasMLXEvolutionBackend"))
    #expect(mlxEvolution.contains("EvolutionaryTrainingBackend"))
    #expect(cliSource.contains("EvolveManas.self"))
    #expect(cliSource.contains("commandName: \"evolve-manas\""))
    #expect(cliSource.contains("LearningCampaignEvolutionRegressionEvaluator"))
    #expect(cliSource.contains("CLICandidateOnlyEvolutionEvaluator"))
    #expect(!cliSource.contains("private struct CLIEvolutionRegressionEvaluator"))
    #expect(cliSource.contains("private func runKuyuRegression"))
    #expect(!cliSource.contains("@MainActor\nprivate final class CLIEvolutionRegressionEvaluator"))
    #expect(!cliSource.contains("@MainActor\nprivate func runKuyuRegression"))
    #expect(cliSource.contains("runRegressionEnvironmentReadiness"))
    #expect(cliSource.contains("EvolutionVariationChoice"))
    #expect(cliSource.contains("EvolutionEvaluationChoice"))
    #expect(cliSource.contains("EvolutionSearchStrategyChoice"))
    #expect(cliSource.contains("EvolutionBootstrapSourceChoice"))
    #expect(cliSource.contains("EvolutionWorldModelUsageChoice"))
    #expect(cliSource.contains("candidateEvaluationConcurrency"))
    #expect(cliSource.contains("--mutation-noise-scale"))
    #expect(cliSource.contains("customLong(\"search-strategy\")"))
    #expect(cliSource.contains("customLong(\"antithetic-sampling\")"))
    #expect(cliSource.contains("customLong(\"adaptive-mutation\")"))
    #expect(cliSource.contains("customLong(\"common-random-seed\")"))
    #expect(cliSource.contains("printEvolutionSearchSummary"))
    #expect(cliSource.contains("bestVsIncumbentDelta"))
    #expect(cliSource.contains("acceptedCheckpoint="))
    #expect(cliSource.contains("if !artifacts.acceptedCheckpoint.accepted"))
    #expect(cliSource.contains("bestCandidate="))
    #expect(cliSource.contains("publishReasons="))
    #expect(cliSource.contains("EvolutionAcceptedCheckpointDecision.fileName"))
    #expect(cliSource.contains("minimumIncumbentImprovement"))
    #expect(cliSource.contains("minimumImprovementOverIncumbent: minimumIncumbentImprovement"))
    #expect(cliSource.contains("minimumNoveltyScore"))
    #expect(cliSource.contains("minimumNoveltyScore: minimumNoveltyScore"))
    #expect(cliSource.contains("qdCells="))
    #expect(cliSource.contains("finalMutationRate="))
    #expect(cliSource.contains("EvolutionQualityDiversityArchive.fileName"))
    #expect(cliSource.contains("no-crossover"))
    #expect(cliSource.contains("checkEvolutionInputs"))
    #expect(cliSource.contains("requiresMLXCheckpoint"))
    #expect(cliSource.contains("0..<episodes"))
    #expect(cliSource.contains("baseDefinitions[index % baseDefinitions.count]"))
    #expect(!orchestrator.contains("mutate"))
    #expect(!orchestrator.contains("crossover"))
}

@Test func xcodeE2EScriptUsesXcodeBuiltBinaryForMLXHarness() throws {
    let script = try readSource("scripts/check-xcode-e2e.sh")
    let readme = try readSource("README.md")

    #expect(script.contains("xcodebuild test"))
    #expect(script.contains("-derivedDataPath"))
    #expect(script.contains("Build/Products/$CONFIGURATION/kuyu"))
    #expect(script.contains("check-kuyu-regression"))
    #expect(script.contains("evolve-manas"))
    #expect(script.contains("accepted-checkpoint.json"))
    #expect(script.contains("evaluation-trace.jsonl"))
    #expect(script.contains("activeEvaluationCountAtStart"))
    #expect(!script.contains("swift run kuyu"))
    #expect(readme.contains("./scripts/check-xcode-e2e.sh"))
    #expect(readme.contains("Xcode is the authority for MLX and Metal-backed execution"))
}

@Test func learningReadinessScriptPreflightsExpensiveCampaignInputs() throws {
    let script = try readSource("scripts/check-learning-readiness.sh")
    let readme = try readSource("README.md")

    #expect(script.contains("KUYU_LEARNING_MIN_FREE_GB"))
    #expect(script.contains("xcodebuild build"))
    #expect(script.contains("check-kuyu-regression"))
    #expect(script.contains("teacherBaseline"))
    #expect(script.contains("bootstrap_train_args=("))
    #expect(script.contains("run_kuyu_plain \"${bootstrap_train_args[@]}\""))
    #expect(script.contains("DEFAULT_BOOTSTRAP_EPISODES=13"))
    #expect(script.contains("DEFAULT_BOOTSTRAP_EPOCHS=3"))
    #expect(script.contains("DEFAULT_BOOTSTRAP_MAX_BATCHES=32"))
    #expect(script.contains("BOOTSTRAP_LR=\"${KUYU_LEARNING_BOOTSTRAP_LR:-0.0001}\""))
    #expect(script.contains("BOOTSTRAP_MLX_SEED=\"${KUYU_LEARNING_BOOTSTRAP_MLX_SEED:-$([[ \"$TASK\" == \"singleLift\" ]] && printf \"11\" || printf \"\")}\""))
    #expect(script.contains("BOOTSTRAP_BIAS_DELTAS=\"${KUYU_LEARNING_BOOTSTRAP_BIAS_DELTAS:-$([[ \"$TASK\" == \"singleLift\" ]] && printf -- \"-0.016,-0.0152,-0.0148,-0.01465,-0.0146,-0.01455,-0.0145,-0.0144,-0.0143,-0.0142,-0.0140,-0.0138,-0.0132,-0.0125,-0.0115,-0.0105,-0.0095,-0.0085,-0.0075,-0.0065\" || printf \"\")}\""))
    #expect(script.contains("select-manas-bias-calibration"))
    #expect(script.contains("bias-calibration-selection.json"))
    #expect(script.contains("\"--deltas=$BOOTSTRAP_BIAS_DELTAS\""))
    #expect(script.contains("strict_checkpoint_passes()"))
    #expect(script.contains("BOOTSTRAP_STRICT_READY=1"))
    #expect(script.contains("bootstrap_rollout_args=("))
    #expect(script.contains("run_kuyu_with_model \"${bootstrap_rollout_args[@]}\""))
    #expect(script.contains("KUYU_LEARNING_REQUIRE_SOURCE_POLICY_PASS"))
    #expect(script.contains("DEFAULT_REQUIRE_SOURCE_POLICY_PASS=1"))
    #expect(script.contains("checkpoint_evaluation_args+=(--require-policy-pass)"))
    #expect(script.contains("--require-policy-pass"))
    #expect(script.contains("source checkpoint regression did not pass readiness"))
    #expect(script.contains("verify_ready_checkpoint_regression()"))
    #expect(script.contains("ready-regression"))
    #expect(script.contains("ready checkpoint regression did not pass readiness"))
    #expect(script.contains("ready=false"))
    #expect(script.contains("failureReasons"))
    #expect(script.contains("checkpoint-evaluation-task-quality-failed"))
    #expect(script.contains("learning-readiness-summary.json"))
    #expect(script.contains("source-regression"))
    #expect(script.contains("ready checkpoint missing file"))
    #expect(!script.contains("policyPassed"))
    #expect(!script.contains("evolve-manas"))
    #expect(!script.contains("swift run kuyu"))
    #expect(readme.contains("./scripts/check-learning-readiness.sh"))
    #expect(readme.contains("low-cost gate"))
}

@Test func rolloutRegressionUsesSingleLiftRuntimeParameterTuning() throws {
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let checkpointEvaluatorSource = try readSource("Sources/KuyuMLX/ManasMLXCheckpointEvaluator.swift")

    #expect(cliSource.contains("hoverThrustScale: hoverScale"))
    #expect(cliSource.contains("KuyuSingleLiftParameterTuning.tuned"))
    #expect(checkpointEvaluatorSource.contains("tunedParametersIfNeeded"))
    #expect(checkpointEvaluatorSource.contains("KuyuSingleLiftParameterTuning.tuned"))
    #expect(!cliSource.contains("maxThrust: 12.0"))
}

@Test func xcodeLearningCampaignScriptPersistsMultiSeedCheckpointProgression() throws {
    let script = try readSource("scripts/run-xcode-learning-campaign.sh")
    let validator = try readSource("scripts/validate-learning-campaign-artifacts.sh")
    let swiftValidator = try readSource("Sources/KuyuMLX/LearningCampaignArtifactValidator.swift")
    let orchestrator = try readSource("Sources/KuyuMLX/LearningCampaignOrchestrator.swift")
    let cliSource = try readSource("Sources/KuyuCLI/KuyuCLI.swift")
    let validateCommand = try readSource("Sources/KuyuCLI/ValidateLearningCampaign.swift")
    let readme = try readSource("README.md")

    #expect(script.contains("xcodebuild build"))
    #expect(script.contains("run-learning-campaign"))
    #expect(script.contains("KUYU_LEARNING_SEED_COUNT"))
    #expect(script.contains("KUYU_LEARNING_SEEDS"))
    #expect(script.contains("--seed-count"))
    #expect(script.contains("KUYU_LEARNING_SEEDS and KUYU_LEARNING_SEED_COUNT cannot both be set"))
    #expect(script.contains("KUYU_LEARNING_NO_QUALITY_GATE is not allowed for learning campaigns"))
    #expect(script.contains("KUYU_LEARNING_GENERATIONS"))
    #expect(script.contains("KUYU_LEARNING_POPULATION"))
    #expect(script.contains("KUYU_LEARNING_SOURCE_CHECKPOINT"))
    #expect(script.contains("KUYU_LEARNING_LOCK_PATH"))
    #expect(script.contains("KUYU_LEARNING_RESUME"))
    #expect(script.contains("another campaign is running"))
    #expect(script.contains("resume is owned by Swift artifacts"))
    #expect(script.contains("validate-learning-campaign --artifact-root"))
    #expect(script.contains("refusing to reuse non-empty artifact root"))
    #expect(script.contains("KUYU_LEARNING_MIN_FREE_GB"))
    #expect(script.contains("incomplete source checkpoint"))
    #expect(!script.contains("train-manas-core"))
    #expect(!script.contains("--export-dataset"))
    #expect(!script.contains("shutil.copytree"))
    #expect(!script.contains("swift run kuyu"))
    #expect(orchestrator.contains("learning-campaign-summary.json"))
    #expect(orchestrator.contains("learning-campaign-plan.json"))
    #expect(orchestrator.contains("learning-campaign-environment.json"))
    #expect(orchestrator.contains("campaign-status.json"))
    #expect(orchestrator.contains("progress.jsonl"))
    #expect(orchestrator.contains("resource-samples.jsonl"))
    #expect(orchestrator.contains("campaign-finished"))
    #expect(orchestrator.contains("acceptedCheckpoint.accepted"))
    #expect(orchestrator.contains("LearningCampaignCheckpointRegressionChecking"))
    #expect(orchestrator.contains("checkpoint-regressions"))
    #expect(orchestrator.contains("parentCheckpointRegressionRejected"))
    #expect(cliSource.contains("LearningCampaignRunner().start"))
    #expect(cliSource.contains("EvolutionRunArtifactValidator().loadAndValidate"))
    #expect(orchestrator.contains("evaluationTraceCount"))
    #expect(orchestrator.contains("overlappedEvaluation"))
    #expect(orchestrator.contains("incumbentFitness"))
    #expect(orchestrator.contains("bestFitness"))
    #expect(orchestrator.contains("bestTaskPassRate"))
    #expect(orchestrator.contains("bestHoldTimeRatio"))
    #expect(readme.contains("./scripts/run-xcode-learning-campaign.sh"))
    #expect(readme.contains("multiple seeds, multiple generations, persistent checkpoints"))
    #expect(readme.contains("KUYU_LEARNING_SEED_COUNT=3"))
    #expect(readme.contains("task-specific source checkpoint"))
    #expect(readme.contains("learning-campaign-plan.json"))
    #expect(readme.contains("learning-campaign-environment.json"))
    #expect(readme.contains("campaign-status.json"))
    #expect(readme.contains("progress.jsonl"))
    #expect(readme.contains("resource-samples.jsonl"))
    #expect(readme.contains("resume is intentionally disabled"))
    #expect(readme.contains("./scripts/validate-learning-campaign-artifacts.sh"))
    #expect(readme.contains("kuyu validate-learning-campaign"))
    #expect(readme.contains("post-run artifact gate"))
    #expect(readme.contains("single-flight campaign lock"))
    #expect(readme.contains("refuses to reuse a non-empty artifact root"))
    #expect(validator.contains("validate-learning-campaign"))
    #expect(validator.contains("swift run kuyu"))
    #expect(validator.contains("KUYU_VALIDATE_ALLOW_FAILED"))
    #expect(swiftValidator.contains("public struct LearningCampaignArtifactValidator"))
    #expect(swiftValidator.contains("EvolutionRunArtifactValidator"))
    #expect(swiftValidator.contains("learning-campaign-validation.json"))
    #expect(swiftValidator.contains("missing-seed-evolution-artifact"))
    #expect(swiftValidator.contains("fitness-count-mismatch"))
    #expect(swiftValidator.contains("incomplete-final-checkpoint"))
    #expect(swiftValidator.contains("missing-parent-task-regression"))
    #expect(swiftValidator.contains("parent-task-regression-failed"))
    #expect(validateCommand.contains("struct ValidateLearningCampaign"))
    #expect(validateCommand.contains("LearningCampaignArtifactValidator"))
    #expect(validateCommand.contains("commandName: \"validate-learning-campaign\""))
    #expect(validateCommand.contains("allowRunning"))
}

@Test func boundedWelcomeCreatesAndOpensKuyuProjects() throws {
    let contentSource = try readSource("Sources/KuyuUI/Views/ContentView.swift")
    let welcomeSource = try readSource("Sources/KuyuUI/Views/BoundedWelcomeView.swift")
    let appModelSource = try readSource("Sources/KuyuUI/Model/AppViewModel.swift")
    let projectSessionSource = try readSource("Sources/KuyuUI/Model/KuyuProjectSession.swift")
    let contentTypesSource = try readSource("Sources/KuyuUI/Model/KuyuProjectContentTypes.swift")
    let boundedInfo = try readBoundedSource("BoundedInfo.plist")

    #expect(contentSource.contains("if model.currentProject == nil"))
    #expect(contentSource.contains("BoundedWelcomeView(model: model)"))
    #expect(!contentSource.contains("NoProjectOpenView"))
    #expect(!contentSource.contains("Open Welcome"))
    #expect(!contentSource.contains("consumeWelcomeWindowRequest()"))
    #expect(!contentSource.contains("welcomeWindowWasRequested"))
    #expect(welcomeSource.contains("public struct BoundedWelcomeWindowContentView"))
    #expect(welcomeSource.contains("BoundedWelcomeView(model: model)"))
    #expect(welcomeSource.contains("@Environment(\\.openWindow)"))
    #expect(welcomeSource.contains("openWindow(id: BoundedWindowID.main.rawValue)"))
    #expect(welcomeSource.contains("NSApp.activate(ignoringOtherApps: true)"))
    #expect(welcomeSource.contains(".onOpenURL"))
    #expect(welcomeSource.contains("model.openURL(url)"))
    #expect(welcomeSource.contains("BoundedWelcomeStep"))
    #expect(welcomeSource.contains("case start"))
    #expect(welcomeSource.contains("case chooseTemplate"))
    #expect(welcomeSource.contains("case configureProject"))
    #expect(welcomeSource.contains("Create New Project"))
    #expect(welcomeSource.contains("Open Existing Project"))
    #expect(welcomeSource.contains("Choose a project template"))
    #expect(welcomeSource.contains("Choose options"))
    #expect(welcomeSource.contains("Picker(\"Platform\""))
    #expect(welcomeSource.contains("LazyVGrid"))
    #expect(welcomeSource.contains("TemplateCard"))
    #expect(welcomeSource.contains("Training Stages"))
    #expect(welcomeSource.contains("Ready Now"))
    #expect(welcomeSource.contains("planned contract"))
    #expect(welcomeSource.contains("template.curriculum.trainingStages"))
    #expect(welcomeSource.contains("template.isRunnableStarter"))
    #expect(welcomeSource.contains("Project Name"))
    #expect(!welcomeSource.contains("List(selection: $selectedTemplateID)"))
    #expect(contentSource.contains(".onOpenURL"))
    #expect(contentSource.contains("model.openURL(url)"))
    #expect(appModelSource.contains("LearningProjectTemplateCatalog.defaultTemplates"))
    #expect(welcomeSource.contains("Open Existing Project"))
    #expect(welcomeSource.contains("Create"))
    #expect(welcomeSource.contains("allowedContentTypes = [.kuyuProject]"))
    #expect(welcomeSource.contains("panel.canChooseFiles = true"))
    #expect(welcomeSource.contains("panel.canChooseDirectories = false"))
    #expect(welcomeSource.contains("panel.treatsFilePackagesAsDirectories = false"))
    #expect(welcomeSource.contains("@State private var parentDirectoryURL: URL?"))
    #expect(welcomeSource.contains("parentDirectoryURL = url"))
    #expect(welcomeSource.contains("parentDirectoryPathBinding"))
    #expect(welcomeSource.contains("homeDirectoryForCurrentUser"))
    #expect(welcomeSource.contains("Developer"))
    #expect(!welcomeSource.contains(".documentDirectory"))
    #expect(appModelSource.contains("currentProject: KuyuProjectSession?"))
    #expect(appModelSource.contains("KuyuProjectFactory()"))
    #expect(appModelSource.contains("KuyuProjectPackageWriter().write"))
    #expect(appModelSource.contains("KuyuProjectPackageLoader().load"))
    #expect(appModelSource.contains("openURL(_ url: URL)"))
    #expect(appModelSource.contains("startAccessingSecurityScopedResource"))
    #expect(appModelSource.contains("stopAccessingSecurityScopedResource"))
    #expect(appModelSource.contains("bookmarkData"))
    #expect(appModelSource.contains("resolvingBookmarkData"))
    #expect(!appModelSource.contains("recentProjectPaths"))
    #expect(!appModelSource.contains("stringArray(forKey"))
    #expect(appModelSource.contains("case \"kuyu\""))
    #expect(appModelSource.contains("case \"manasbundle\""))
    #expect(appModelSource.contains("openModelBundle(at: url)"))
    #expect(appModelSource.contains("validateProjectSession(package)"))
    #expect(appModelSource.contains("requiresModelBundleCompatibility"))
    #expect(appModelSource.contains("KuyuProjectSessionError.missingSourceBundle"))
    #expect(appModelSource.contains("prepareRunnableProjectAssets"))
    #expect(projectSessionSource.contains("KuyuProjectPackage"))
    #expect(contentTypesSource.contains("team.stamp.kuyu-project"))
    #expect(contentTypesSource.contains("team.stamp.manas-bundle"))
    #expect(boundedInfo.contains("CFBundleDocumentTypes"))
    #expect(boundedInfo.contains("team.stamp.kuyu-project"))
    #expect(boundedInfo.contains("team.stamp.manas-bundle"))
    #expect(boundedInfo.contains("KuyuProjectDocumentIcon"))
    #expect(boundedInfo.contains("ManasBundleDocumentIcon"))
}

private func readSource(_ relativePath: String) throws -> String {
    let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
    let url = root.appendingPathComponent(relativePath)
    return try String(contentsOf: url, encoding: .utf8)
}

private func readTrainingSource(_ relativePath: String) throws -> String {
    let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("kuyu-training", isDirectory: true)
    let url = root.appendingPathComponent(relativePath)
    return try String(contentsOf: url, encoding: .utf8)
}

private func readBoundedSource(_ relativePath: String) throws -> String {
    let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("Bounded", isDirectory: true)
    let url = root.appendingPathComponent(relativePath)
    return try String(contentsOf: url, encoding: .utf8)
}
